/*
 This file was autogenerated by tags.py 
 */

#import "GCRelationship.h"

@class GCAdoptedByWhichParentAttribute;

/**
 
*/
@interface GCAdoptedIntoFamilyRelationship : GCRelationship

// Methods:
/** Initializes and returns a adoptedIntoFamily.

 
 @return A new adoptedIntoFamily.
*/
+(GCAdoptedIntoFamilyRelationship *)adoptedIntoFamily;

// Properties:
/// . 
@property (nonatomic) GCAdoptedByWhichParentAttribute *adoptedByWhichParent;


@end

