/*
 This file was autogenerated by tags.py 
 */

#import "GCEventDetailAttribute.h"



/**
 
*/
@interface GCAgeAttribute : GCEventDetailAttribute

// Methods:
/** Initializes and returns a age.

 
 @return A new age.
*/
+(instancetype)age;
/** Initializes and returns a age.

 @param value The value as a GCValue object.
 @return A new age.
*/
+(instancetype)ageWithValue:(GCValue *)value;
/** Initializes and returns a age.

 @param value The value as an NSString.
 @return A new age.
*/
+(instancetype)ageWithGedcomStringValue:(NSString *)value;

// Properties:


@end

