/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCAncestralFileNumberAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a ancestralFileNumber.

 
 @return A new ancestralFileNumber.
*/
+(instancetype)ancestralFileNumber;
/// @name Initializing

/** Initializes and returns a ancestralFileNumber.

 @param value The value as a GCValue object.
 @return A new ancestralFileNumber.
*/
+(instancetype)ancestralFileNumberWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a ancestralFileNumber.

 @param value The value as an NSString.
 @return A new ancestralFileNumber.
*/
+(instancetype)ancestralFileNumberWithGedcomStringValue:(NSString *)value;

// Properties:


@end
