/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCAuthorAttribute : GCAttribute

// Methods:
/** Initializes and returns a author.

 
 @return A new author.
*/
+(instancetype)author;
/** Initializes and returns a author.

 @param value The value as a GCValue object.
 @return A new author.
*/
+(instancetype)authorWithValue:(GCValue *)value;
/** Initializes and returns a author.

 @param value The value as an NSString.
 @return A new author.
*/
+(instancetype)authorWithGedcomStringValue:(NSString *)value;

// Properties:


@end

