/*
 This file was autogenerated by tags.py 
 */

#import "GCRelationship.h"



/**
 
*/
@interface GCBornToFamilyRelationship : GCRelationship

// Methods:
/** Initializes and returns a bornToFamily.

 
 @return A new bornToFamily.
*/
+(instancetype)bornToFamily;

// Properties:


@end

