/*
 This file was autogenerated by tags.py 
 */

#import "GCEventDetailAttribute.h"



/**
 
*/
@interface GCCauseAttribute : GCEventDetailAttribute

// Methods:
/** Initializes and returns a cause.

 
 @return A new cause.
*/
+(instancetype)cause;
/** Initializes and returns a cause.

 @param value The value as a GCValue object.
 @return A new cause.
*/
+(instancetype)causeWithValue:(GCValue *)value;
/** Initializes and returns a cause.

 @param value The value as an NSString.
 @return A new cause.
*/
+(instancetype)causeWithGedcomStringValue:(NSString *)value;

// Properties:


@end

