/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCCauseAttribute : GCAttribute

// Methods:
/** Initializes and returns a cause.

 
 @return A new cause.
*/
+(GCCauseAttribute *)cause;
/** Initializes and returns a cause.

 @param value The value as a GCValue object.
 @return A new cause.
*/
+(GCCauseAttribute *)causeWithValue:(GCValue *)value;
/** Initializes and returns a cause.

 @param value The value as an NSString.
 @return A new cause.
*/
+(GCCauseAttribute *)causeWithGedcomStringValue:(NSString *)value;

// Properties:


@end

