/*
 This file was autogenerated by tags.py 
 */

#import "GCFamilyEventAttribute.h"

@class GCHusbandDetailAttribute;
@class GCWifeDetailAttribute;

/**
 
*/
@interface GCCensusAttribute : GCFamilyEventAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a census.

 
 @return A new census.
*/
+(instancetype)census;
/// @name Initializing

/** Initializes and returns a census.

 @param value The value as a GCValue object.
 @return A new census.
*/
+(instancetype)censusWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a census.

 @param value The value as an NSString.
 @return A new census.
*/
+(instancetype)censusWithGedcomStringValue:(NSString *)value;

// Properties:
/// . 
@property (nonatomic) GCHusbandDetailAttribute *husbandDetail;

/// . 
@property (nonatomic) GCWifeDetailAttribute *wifeDetail;


@end
