/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCDescriptiveNameAttribute : GCAttribute

// Methods:
/** Initializes and returns a descriptiveName.

 
 @return A new descriptiveName.
*/
+(instancetype)descriptiveName;
/** Initializes and returns a descriptiveName.

 @param value The value as a GCValue object.
 @return A new descriptiveName.
*/
+(instancetype)descriptiveNameWithValue:(GCValue *)value;
/** Initializes and returns a descriptiveName.

 @param value The value as an NSString.
 @return A new descriptiveName.
*/
+(instancetype)descriptiveNameWithGedcomStringValue:(NSString *)value;

// Properties:


@end

