/*
 This file was autogenerated by tags.py 
 */

#import "GCFamilyEventAttribute.h"

@class GCHusbandDetailAttribute;
@class GCWifeDetailAttribute;

/**
 
*/
@interface GCDivorceFiledAttribute : GCFamilyEventAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a divorceFiled.

 
 @return A new divorceFiled.
*/
+(instancetype)divorceFiled;
/// @name Initializing

/** Initializes and returns a divorceFiled.

 @param value The value as a GCValue object.
 @return A new divorceFiled.
*/
+(instancetype)divorceFiledWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a divorceFiled.

 @param value The value as an NSString.
 @return A new divorceFiled.
*/
+(instancetype)divorceFiledWithGedcomStringValue:(NSString *)value;

// Properties:
/// . 
@property (nonatomic) GCHusbandDetailAttribute *husbandDetail;

/// . 
@property (nonatomic) GCWifeDetailAttribute *wifeDetail;


@end
