/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCGenerationsOfAncestorsAttribute : GCAttribute

// Methods:
/** Initializes and returns a generationsOfAncestors.

 
 @return A new generationsOfAncestors.
*/
+(instancetype)generationsOfAncestors;
/** Initializes and returns a generationsOfAncestors.

 @param value The value as a GCValue object.
 @return A new generationsOfAncestors.
*/
+(instancetype)generationsOfAncestorsWithValue:(GCValue *)value;
/** Initializes and returns a generationsOfAncestors.

 @param value The value as an NSString.
 @return A new generationsOfAncestors.
*/
+(instancetype)generationsOfAncestorsWithGedcomStringValue:(NSString *)value;

// Properties:


@end

