/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"

@class GCGedcomFormatAttribute;
@class GCVersionAttribute;

/**
 
*/
@interface GCGedcomAttribute : GCAttribute

// Methods:
/** Initializes and returns a gedcom.

 
 @return A new gedcom.
*/
+(GCGedcomAttribute *)gedcom;
/** Initializes and returns a gedcom.

 @param value The value as a GCValue object.
 @return A new gedcom.
*/
+(GCGedcomAttribute *)gedcomWithValue:(GCValue *)value;
/** Initializes and returns a gedcom.

 @param value The value as an NSString.
 @return A new gedcom.
*/
+(GCGedcomAttribute *)gedcomWithGedcomStringValue:(NSString *)value;

// Properties:
/// .  NB: required property.
@property (nonatomic) GCVersionAttribute *version;

/// .  NB: required property.
@property (nonatomic) GCGedcomFormatAttribute *gedcomFormat;


@end

