/*
 This file was autogenerated by tags.py 
 */

#import "GCRecord.h"

@class GCAdoptionAttribute;
@class GCAdultChristeningAttribute;
@class GCAliasRelationship;
@class GCAncestorInterestRelationship;
@class GCAncestralFileNumberAttribute;
@class GCAssociationRelationship;
@class GCBaptismAttribute;
@class GCBarMitzvahAttribute;
@class GCBasMitzvahAttribute;
@class GCBirthAttribute;
@class GCBlessingAttribute;
@class GCBurialAttribute;
@class GCCasteAttribute;
@class GCCensusAttribute;
@class GCChangeInfoAttribute;
@class GCChildInFamilyRelationship;
@class GCChristeningAttribute;
@class GCConfirmationAttribute;
@class GCCremationAttribute;
@class GCDeathAttribute;
@class GCDescendantInterestRelationship;
@class GCEducationAttribute;
@class GCEmigrationAttribute;
@class GCFirstCommunionAttribute;
@class GCGenerationsOfDescendantsAttribute;
@class GCGenericEventAttribute;
@class GCGraduationAttribute;
@class GCIdentNumberAttribute;
@class GCImmigrationAttribute;
@class GCLDSBaptismAttribute;
@class GCLDSConfirmationAttribute;
@class GCLDSEndowmentAttribute;
@class GCLDSSealingChildAttribute;
@class GCMultimediaEmbeddedAttribute;
@class GCMultimediaReferenceRelationship;
@class GCNationalityAttribute;
@class GCNaturalizationAttribute;
@class GCNoteEmbeddedAttribute;
@class GCNoteReferenceRelationship;
@class GCNumberOfChildrenAttribute;
@class GCNumberOfMarriagesAttribute;
@class GCOccupationAttribute;
@class GCOrdinationAttribute;
@class GCPersonalNameAttribute;
@class GCPhysicalDescriptionAttribute;
@class GCProbateAttribute;
@class GCPropertyOwnedAttribute;
@class GCRecordFileNumberAttribute;
@class GCRecordIdNumberAttribute;
@class GCReligionAttribute;
@class GCResidenceAttribute;
@class GCRestrictionNoticeAttribute;
@class GCRetirementAttribute;
@class GCSexAttribute;
@class GCSocialSecurityNumberAttribute;
@class GCSourceCitationRelationship;
@class GCSourceEmbeddedAttribute;
@class GCSpouseInFamilyRelationship;
@class GCSubmitterReferenceRelationship;
@class GCTitleAttribute;
@class GCUserReferenceNumberAttribute;
@class GCWillAttribute;

/**
 The individual record is a compilation of facts, known or discovered, about an individual. Sometimes these facts are from different sources. This form allows documentation of the source where each of the facts were discovered.
*/
@interface GCIndividualRecord : GCRecord

// Methods:
/** Initializes and returns a individual.

 @param context The context in which to create the entity.
 @return A new individual.
*/
+(instancetype)individualInContext:(GCContext *)context;

// Properties:
/// . 
@property (nonatomic) GCRestrictionNoticeAttribute *restrictionNotice;

/// . GCPersonalNameAttribute
@property (nonatomic) NSArray *personalNames;
/// . personalNames
@property (nonatomic) NSMutableArray *mutablePersonalNames;

/// . 
@property (nonatomic) GCSexAttribute *sex;

/// Property for accessing the following properties
@property (nonatomic) NSArray *individualEvents;

/// Also contained in individualEvents. . GCBirthAttribute
@property (nonatomic) NSArray *births;
/// Also contained in individualEvents. . births
@property (nonatomic) NSMutableArray *mutableBirths;

/// Also contained in individualEvents. . GCChristeningAttribute
@property (nonatomic) NSArray *christenings;
/// Also contained in individualEvents. . christenings
@property (nonatomic) NSMutableArray *mutableChristenings;

/// Also contained in individualEvents. . GCDeathAttribute
@property (nonatomic) NSArray *deaths;
/// Also contained in individualEvents. . deaths
@property (nonatomic) NSMutableArray *mutableDeaths;

/// Also contained in individualEvents. . GCBurialAttribute
@property (nonatomic) NSArray *burials;
/// Also contained in individualEvents. . burials
@property (nonatomic) NSMutableArray *mutableBurials;

/// Also contained in individualEvents. . GCCremationAttribute
@property (nonatomic) NSArray *cremations;
/// Also contained in individualEvents. . cremations
@property (nonatomic) NSMutableArray *mutableCremations;

/// Also contained in individualEvents. . GCAdoptionAttribute
@property (nonatomic) NSArray *adoptions;
/// Also contained in individualEvents. . adoptions
@property (nonatomic) NSMutableArray *mutableAdoptions;

/// Also contained in individualEvents. . GCBaptismAttribute
@property (nonatomic) NSArray *baptisms;
/// Also contained in individualEvents. . baptisms
@property (nonatomic) NSMutableArray *mutableBaptisms;

/// Also contained in individualEvents. . GCBarMitzvahAttribute
@property (nonatomic) NSArray *barMitzvahs;
/// Also contained in individualEvents. . barMitzvahs
@property (nonatomic) NSMutableArray *mutableBarMitzvahs;

/// Also contained in individualEvents. . GCBasMitzvahAttribute
@property (nonatomic) NSArray *basMitzvahs;
/// Also contained in individualEvents. . basMitzvahs
@property (nonatomic) NSMutableArray *mutableBasMitzvahs;

/// Also contained in individualEvents. . GCBlessingAttribute
@property (nonatomic) NSArray *blessings;
/// Also contained in individualEvents. . blessings
@property (nonatomic) NSMutableArray *mutableBlessings;

/// Also contained in individualEvents. . GCAdultChristeningAttribute
@property (nonatomic) NSArray *adultChristenings;
/// Also contained in individualEvents. . adultChristenings
@property (nonatomic) NSMutableArray *mutableAdultChristenings;

/// Also contained in individualEvents. . GCConfirmationAttribute
@property (nonatomic) NSArray *confirmations;
/// Also contained in individualEvents. . confirmations
@property (nonatomic) NSMutableArray *mutableConfirmations;

/// Also contained in individualEvents. . GCFirstCommunionAttribute
@property (nonatomic) NSArray *firstCommunions;
/// Also contained in individualEvents. . firstCommunions
@property (nonatomic) NSMutableArray *mutableFirstCommunions;

/// Also contained in individualEvents. . GCOrdinationAttribute
@property (nonatomic) NSArray *ordinations;
/// Also contained in individualEvents. . ordinations
@property (nonatomic) NSMutableArray *mutableOrdinations;

/// Also contained in individualEvents. . GCNaturalizationAttribute
@property (nonatomic) NSArray *naturalizations;
/// Also contained in individualEvents. . naturalizations
@property (nonatomic) NSMutableArray *mutableNaturalizations;

/// Also contained in individualEvents. . GCEmigrationAttribute
@property (nonatomic) NSArray *emigrations;
/// Also contained in individualEvents. . emigrations
@property (nonatomic) NSMutableArray *mutableEmigrations;

/// Also contained in individualEvents. . GCImmigrationAttribute
@property (nonatomic) NSArray *immigrations;
/// Also contained in individualEvents. . immigrations
@property (nonatomic) NSMutableArray *mutableImmigrations;

/// Also contained in individualEvents. . GCCensusAttribute
@property (nonatomic) NSArray *censuses;
/// Also contained in individualEvents. . censuses
@property (nonatomic) NSMutableArray *mutableCensuses;

/// Also contained in individualEvents. . GCProbateAttribute
@property (nonatomic) NSArray *probates;
/// Also contained in individualEvents. . probates
@property (nonatomic) NSMutableArray *mutableProbates;

/// Also contained in individualEvents. . GCWillAttribute
@property (nonatomic) NSArray *wills;
/// Also contained in individualEvents. . wills
@property (nonatomic) NSMutableArray *mutableWills;

/// Also contained in individualEvents. . GCGraduationAttribute
@property (nonatomic) NSArray *graduations;
/// Also contained in individualEvents. . graduations
@property (nonatomic) NSMutableArray *mutableGraduations;

/// Also contained in individualEvents. . GCRetirementAttribute
@property (nonatomic) NSArray *retirements;
/// Also contained in individualEvents. . retirements
@property (nonatomic) NSMutableArray *mutableRetirements;

/// Also contained in individualEvents. . GCGenericEventAttribute
@property (nonatomic) NSArray *genericEvents;
/// Also contained in individualEvents. . genericEvents
@property (nonatomic) NSMutableArray *mutableGenericEvents;

/// Property for accessing the following properties
@property (nonatomic) NSArray *individualAttributes;

/// Also contained in individualAttributes. . GCCasteAttribute
@property (nonatomic) NSArray *castes;
/// Also contained in individualAttributes. . castes
@property (nonatomic) NSMutableArray *mutableCastes;

/// Also contained in individualAttributes. . GCPhysicalDescriptionAttribute
@property (nonatomic) NSArray *physicalDescriptions;
/// Also contained in individualAttributes. . physicalDescriptions
@property (nonatomic) NSMutableArray *mutablePhysicalDescriptions;

/// Also contained in individualAttributes. . GCGenerationsOfDescendantsAttribute
@property (nonatomic) NSArray *generationsOfDescendantss;
/// Also contained in individualAttributes. . generationsOfDescendantss
@property (nonatomic) NSMutableArray *mutableGenerationsOfDescendantss;

/// Also contained in individualAttributes. . GCEducationAttribute
@property (nonatomic) NSArray *educations;
/// Also contained in individualAttributes. . educations
@property (nonatomic) NSMutableArray *mutableEducations;

/// Also contained in individualAttributes. . GCIdentNumberAttribute
@property (nonatomic) NSArray *identNumbers;
/// Also contained in individualAttributes. . identNumbers
@property (nonatomic) NSMutableArray *mutableIdentNumbers;

/// Also contained in individualAttributes. . GCNationalityAttribute
@property (nonatomic) NSArray *nationalities;
/// Also contained in individualAttributes. . nationalities
@property (nonatomic) NSMutableArray *mutableNationalities;

/// Also contained in individualAttributes. . GCNumberOfChildrenAttribute
@property (nonatomic) NSArray *numberOfChildrens;
/// Also contained in individualAttributes. . numberOfChildrens
@property (nonatomic) NSMutableArray *mutableNumberOfChildrens;

/// Also contained in individualAttributes. . GCNumberOfMarriagesAttribute
@property (nonatomic) NSArray *numberOfMarriagess;
/// Also contained in individualAttributes. . numberOfMarriagess
@property (nonatomic) NSMutableArray *mutableNumberOfMarriagess;

/// Also contained in individualAttributes. . GCOccupationAttribute
@property (nonatomic) NSArray *occupations;
/// Also contained in individualAttributes. . occupations
@property (nonatomic) NSMutableArray *mutableOccupations;

/// Also contained in individualAttributes. . GCPropertyOwnedAttribute
@property (nonatomic) NSArray *propertyOwneds;
/// Also contained in individualAttributes. . propertyOwneds
@property (nonatomic) NSMutableArray *mutablePropertyOwneds;

/// Also contained in individualAttributes. . GCReligionAttribute
@property (nonatomic) NSArray *religions;
/// Also contained in individualAttributes. . religions
@property (nonatomic) NSMutableArray *mutableReligions;

/// Also contained in individualAttributes. . GCResidenceAttribute
@property (nonatomic) NSArray *residences;
/// Also contained in individualAttributes. . residences
@property (nonatomic) NSMutableArray *mutableResidences;

/// Also contained in individualAttributes. . GCSocialSecurityNumberAttribute
@property (nonatomic) NSArray *socialSecurityNumbers;
/// Also contained in individualAttributes. . socialSecurityNumbers
@property (nonatomic) NSMutableArray *mutableSocialSecurityNumbers;

/// Also contained in individualAttributes. . GCTitleAttribute
@property (nonatomic) NSArray *titles;
/// Also contained in individualAttributes. . titles
@property (nonatomic) NSMutableArray *mutableTitles;

/// Property for accessing the following properties
@property (nonatomic) NSArray *individualLDSOrdinances;

/// Also contained in individualLDSOrdinances. . GCLDSBaptismAttribute
@property (nonatomic) NSArray *lDSBaptisms;
/// Also contained in individualLDSOrdinances. . lDSBaptisms
@property (nonatomic) NSMutableArray *mutableLDSBaptisms;

/// Also contained in individualLDSOrdinances. . GCLDSConfirmationAttribute
@property (nonatomic) NSArray *lDSConfirmations;
/// Also contained in individualLDSOrdinances. . lDSConfirmations
@property (nonatomic) NSMutableArray *mutableLDSConfirmations;

/// Also contained in individualLDSOrdinances. . GCLDSEndowmentAttribute
@property (nonatomic) NSArray *lDSEndowments;
/// Also contained in individualLDSOrdinances. . lDSEndowments
@property (nonatomic) NSMutableArray *mutableLDSEndowments;

/// Also contained in individualLDSOrdinances. . GCLDSSealingChildAttribute
@property (nonatomic) NSArray *lDSSealingChilds;
/// Also contained in individualLDSOrdinances. . lDSSealingChilds
@property (nonatomic) NSMutableArray *mutableLDSSealingChilds;

/// . GCChildInFamilyRelationship
@property (nonatomic) NSArray *childInFamilies;
/// . childInFamilies
@property (nonatomic) NSMutableArray *mutableChildInFamilies;

/// . GCSpouseInFamilyRelationship
@property (nonatomic) NSArray *spouseInFamilies;
/// . spouseInFamilies
@property (nonatomic) NSMutableArray *mutableSpouseInFamilies;

/// . GCSubmitterReferenceRelationship
@property (nonatomic) NSArray *submitterReferences;
/// . submitterReferences
@property (nonatomic) NSMutableArray *mutableSubmitterReferences;

/// . GCAssociationRelationship
@property (nonatomic) NSArray *associations;
/// . associations
@property (nonatomic) NSMutableArray *mutableAssociations;

/// . GCAliasRelationship
@property (nonatomic) NSArray *aliases;
/// . aliases
@property (nonatomic) NSMutableArray *mutableAliases;

/// . GCAncestorInterestRelationship
@property (nonatomic) NSArray *ancestorInterests;
/// . ancestorInterests
@property (nonatomic) NSMutableArray *mutableAncestorInterests;

/// . GCDescendantInterestRelationship
@property (nonatomic) NSArray *descendantInterests;
/// . descendantInterests
@property (nonatomic) NSMutableArray *mutableDescendantInterests;

/// Property for accessing the following properties
@property (nonatomic) NSArray *sources;

/// Also contained in sources. . GCSourceCitationRelationship
@property (nonatomic) NSArray *sourceCitations;
/// Also contained in sources. . sourceCitations
@property (nonatomic) NSMutableArray *mutableSourceCitations;

/// Also contained in sources. . GCSourceEmbeddedAttribute
@property (nonatomic) NSArray *sourceEmbeddeds;
/// Also contained in sources. . sourceEmbeddeds
@property (nonatomic) NSMutableArray *mutableSourceEmbeddeds;

/// Property for accessing the following properties
@property (nonatomic) NSArray *multimedias;

/// Also contained in multimedias. . GCMultimediaReferenceRelationship
@property (nonatomic) NSArray *multimediaReferences;
/// Also contained in multimedias. . multimediaReferences
@property (nonatomic) NSMutableArray *mutableMultimediaReferences;

/// Also contained in multimedias. . GCMultimediaEmbeddedAttribute
@property (nonatomic) NSArray *multimediaEmbeddeds;
/// Also contained in multimedias. . multimediaEmbeddeds
@property (nonatomic) NSMutableArray *mutableMultimediaEmbeddeds;

/// Property for accessing the following properties
@property (nonatomic) NSArray *notes;

/// Also contained in notes. . GCNoteReferenceRelationship
@property (nonatomic) NSArray *noteReferences;
/// Also contained in notes. . noteReferences
@property (nonatomic) NSMutableArray *mutableNoteReferences;

/// Also contained in notes. . GCNoteEmbeddedAttribute
@property (nonatomic) NSArray *noteEmbeddeds;
/// Also contained in notes. . noteEmbeddeds
@property (nonatomic) NSMutableArray *mutableNoteEmbeddeds;

/// . GCRecordFileNumberAttribute
@property (nonatomic) NSArray *recordFileNumbers;
/// . recordFileNumbers
@property (nonatomic) NSMutableArray *mutableRecordFileNumbers;

/// . GCAncestralFileNumberAttribute
@property (nonatomic) NSArray *ancestralFileNumbers;
/// . ancestralFileNumbers
@property (nonatomic) NSMutableArray *mutableAncestralFileNumbers;

/// . GCUserReferenceNumberAttribute
@property (nonatomic) NSArray *userReferenceNumbers;
/// . userReferenceNumbers
@property (nonatomic) NSMutableArray *mutableUserReferenceNumbers;

/// . 
@property (nonatomic) GCRecordIdNumberAttribute *recordIdNumber;

/// . 
@property (nonatomic) GCChangeInfoAttribute *changeInfo;


@end

