/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCLanguageAttribute : GCAttribute

// Methods:
/** Initializes and returns a language.

 
 @return A new language.
*/
+(GCLanguageAttribute *)language;
/** Initializes and returns a language.

 @param value The value as a GCValue object.
 @return A new language.
*/
+(GCLanguageAttribute *)languageWithValue:(GCValue *)value;
/** Initializes and returns a language.

 @param value The value as an NSString.
 @return A new language.
*/
+(GCLanguageAttribute *)languageWithGedcomStringValue:(NSString *)value;

// Properties:


@end

