/*
 This file was autogenerated by tags.py 
 */

#import "GCIndividualLDSOrdinanceAttribute.h"

@class GCLDSSealingChildStatusAttribute;
@class GCSealedToFamilyRelationship;

/**
 
*/
@interface GCLDSSealingChildAttribute : GCIndividualLDSOrdinanceAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a lDSSealingChild.

 
 @return A new lDSSealingChild.
*/
+(instancetype)lDSSealingChild;
/// @name Initializing

/** Initializes and returns a lDSSealingChild.

 @param value The value as a GCValue object.
 @return A new lDSSealingChild.
*/
+(instancetype)lDSSealingChildWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a lDSSealingChild.

 @param value The value as an NSString.
 @return A new lDSSealingChild.
*/
+(instancetype)lDSSealingChildWithGedcomStringValue:(NSString *)value;

// Properties:
/// . 
@property (nonatomic) GCLDSSealingChildStatusAttribute *lDSSealingChildStatus;

/// .  NB: required property.
@property (nonatomic) GCSealedToFamilyRelationship *sealedToFamily;


@end
