/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCLDSSealingChildStatusAttribute : GCAttribute

// Methods:
/** Initializes and returns a lDSSealingChildStatus.

 
 @return A new lDSSealingChildStatus.
*/
+(instancetype)lDSSealingChildStatus;
/** Initializes and returns a lDSSealingChildStatus.

 @param value The value as a GCValue object.
 @return A new lDSSealingChildStatus.
*/
+(instancetype)lDSSealingChildStatusWithValue:(GCValue *)value;
/** Initializes and returns a lDSSealingChildStatus.

 @param value The value as an NSString.
 @return A new lDSSealingChildStatus.
*/
+(instancetype)lDSSealingChildStatusWithGedcomStringValue:(NSString *)value;

// Properties:


@end

