/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCNameSuffixAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a nameSuffix.

 
 @return A new nameSuffix.
*/
+(instancetype)nameSuffix;
/// @name Initializing

/** Initializes and returns a nameSuffix.

 @param value The value as a GCValue object.
 @return A new nameSuffix.
*/
+(instancetype)nameSuffixWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a nameSuffix.

 @param value The value as an NSString.
 @return A new nameSuffix.
*/
+(instancetype)nameSuffixWithGedcomStringValue:(NSString *)value;

// Properties:


@end
