/*
 This file was autogenerated by tags.py 
 */

#import "GCIndividualAttributeAttribute.h"



/**
 
*/
@interface GCOccupationAttribute : GCIndividualAttributeAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a occupation.

 
 @return A new occupation.
*/
+(instancetype)occupation;
/// @name Initializing

/** Initializes and returns a occupation.

 @param value The value as a GCValue object.
 @return A new occupation.
*/
+(instancetype)occupationWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a occupation.

 @param value The value as an NSString.
 @return A new occupation.
*/
+(instancetype)occupationWithGedcomStringValue:(NSString *)value;

// Properties:


@end
