/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCOrdinanceFlagAttribute : GCAttribute

// Methods:
/** Initializes and returns a ordinanceFlag.

 
 @return A new ordinanceFlag.
*/
+(GCOrdinanceFlagAttribute *)ordinanceFlag;
/** Initializes and returns a ordinanceFlag.

 @param value The value as a GCValue object.
 @return A new ordinanceFlag.
*/
+(GCOrdinanceFlagAttribute *)ordinanceFlagWithValue:(GCValue *)value;
/** Initializes and returns a ordinanceFlag.

 @param value The value as an NSString.
 @return A new ordinanceFlag.
*/
+(GCOrdinanceFlagAttribute *)ordinanceFlagWithGedcomStringValue:(NSString *)value;

// Properties:


@end

