/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCPageAttribute : GCAttribute

// Methods:
/** Initializes and returns a page.

 
 @return A new page.
*/
+(instancetype)page;
/** Initializes and returns a page.

 @param value The value as a GCValue object.
 @return A new page.
*/
+(instancetype)pageWithValue:(GCValue *)value;
/** Initializes and returns a page.

 @param value The value as an NSString.
 @return A new page.
*/
+(instancetype)pageWithGedcomStringValue:(NSString *)value;

// Properties:


@end

