/*
 This file was autogenerated by tags.py 
 */

#import "GCRelationship.h"



/**
 
*/
@interface GCSealedToFamilyRelationship : GCRelationship

// Methods:
/// @name Initializing

/** Initializes and returns a sealedToFamily.

 
 @return A new sealedToFamily.
*/
+(instancetype)sealedToFamily;

// Properties:


@end

