/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"

@class GCEventsRecordedAttribute;
@class GCNoteEmbeddedAttribute;
@class GCNoteReferenceRelationship;
@class GCResponsibleAgencyAttribute;

/**
 
*/
@interface GCSourceDataAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a sourceData.

 
 @return A new sourceData.
*/
+(instancetype)sourceData;
/// @name Initializing

/** Initializes and returns a sourceData.

 @param value The value as a GCValue object.
 @return A new sourceData.
*/
+(instancetype)sourceDataWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a sourceData.

 @param value The value as an NSString.
 @return A new sourceData.
*/
+(instancetype)sourceDataWithGedcomStringValue:(NSString *)value;

// Properties:
/// . GCEventsRecordedAttribute
@property (nonatomic) NSArray *eventsRecordeds;
/// . Contains instances of eventsRecordeds
@property (nonatomic) NSMutableArray *mutableEventsRecordeds;

/// . 
@property (nonatomic) GCResponsibleAgencyAttribute *responsibleAgency;

/// @name Accessing notes

/// Property for accessing the following properties
@property (nonatomic) NSArray *notes;

/// @name Accessing notes 

///Also contained in notes. . GCNoteReferenceRelationship
@property (nonatomic) NSArray *noteReferences;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteReferences
@property (nonatomic) NSMutableArray *mutableNoteReferences;

/// @name Accessing notes 

///Also contained in notes. . GCNoteEmbeddedAttribute
@property (nonatomic) NSArray *noteEmbeddeds;
/// @name Accessing notes 

///Also contained in notes. . Contains instances of noteEmbeddeds
@property (nonatomic) NSMutableArray *mutableNoteEmbeddeds;


@end
