/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCSurnamePrefixAttribute : GCAttribute

// Methods:
/// @name Initializing

/** Initializes and returns a surnamePrefix.

 
 @return A new surnamePrefix.
*/
+(instancetype)surnamePrefix;
/// @name Initializing

/** Initializes and returns a surnamePrefix.

 @param value The value as a GCValue object.
 @return A new surnamePrefix.
*/
+(instancetype)surnamePrefixWithValue:(GCValue *)value;
/// @name Initializing

/** Initializes and returns a surnamePrefix.

 @param value The value as an NSString.
 @return A new surnamePrefix.
*/
+(instancetype)surnamePrefixWithGedcomStringValue:(NSString *)value;

// Properties:


@end
