/*
 This file was autogenerated by tags.py 
 */

#import "GCRelationship.h"



/**
 
*/
@interface GCSubmissionReferenceRelationship : GCRelationship

// Methods:
/** Initializes and returns a submissionReference.

 
 @return A new submissionReference.
*/
+(GCSubmissionReferenceRelationship *)submissionReference;

// Properties:


@end

