/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCTextAttribute : GCAttribute

// Methods:
/** Initializes and returns a text.

 
 @return A new text.
*/
+(instancetype)text;
/** Initializes and returns a text.

 @param value The value as a GCValue object.
 @return A new text.
*/
+(instancetype)textWithValue:(GCValue *)value;
/** Initializes and returns a text.

 @param value The value as an NSString.
 @return A new text.
*/
+(instancetype)textWithGedcomStringValue:(NSString *)value;

// Properties:


@end

