/*
 This file was autogenerated by tags.py 
 */

#import "GCAttribute.h"



/**
 
*/
@interface GCVersionAttribute : GCAttribute

// Methods:
/** Initializes and returns a version.

 
 @return A new version.
*/
+(GCVersionAttribute *)version;
/** Initializes and returns a version.

 @param value The value as a GCValue object.
 @return A new version.
*/
+(GCVersionAttribute *)versionWithValue:(GCValue *)value;
/** Initializes and returns a version.

 @param value The value as an NSString.
 @return A new version.
*/
+(GCVersionAttribute *)versionWithGedcomStringValue:(NSString *)value;

// Properties:


@end

