/*
 This file was autogenerated by tags.py 
 */

#import "GCEntity.h"
#import "GCAttribute.h"
#import "GCRelationship.h"

#pragma mark Forward declarations

@class GCAbbreviationAttribute;
@class GCAddressAttribute;
@class GCAddressLine1Attribute;
@class GCAddressLine2Attribute;
@class GCAncestralFileNumberAttribute;
@class GCAuthorAttribute;
@class GCChildInFamilyRelationship;
@class GCCityAttribute;
@class GCCorporationAttribute;
@class GCCountryAttribute;
@class GCDataAttribute;
@class GCDateAttribute;
@class GCFamilyFileAttribute;
@class GCFileAttribute;
@class GCFormatAttribute;
@class GCGenerationsOfAncestorsAttribute;
@class GCGenerationsOfDescendantsAttribute;
@class GCGivenNameAttribute;
@class GCHusbandRelationship;
@class GCLanguageAttribute;
@class GCNameAttribute;
@class GCNamePrefixAttribute;
@class GCNameSuffixAttribute;
@class GCNicknameAttribute;
@class GCNumberOfChildrenAttribute;
@class GCOrdinanceAttribute;
@class GCPageAttribute;
@class GCPedigreeAttribute;
@class GCPhoneNumberAttribute;
@class GCPlaceAttribute;
@class GCPostalCodeAttribute;
@class GCPublicationFactsAttribute;
@class GCQualityOfDataAttribute;
@class GCRecordFileNumberAttribute;
@class GCRecordIdNumberAttribute;
@class GCRelationshipDescriptorAttribute;
@class GCRepositoryCitationRelationship;
@class GCResponsibleAgencyAttribute;
@class GCRestrictionNoticeAttribute;
@class GCSexAttribute;
@class GCSourceDataAttribute;
@class GCStateAttribute;
@class GCSubmitterReferenceRelationship;
@class GCSurnameAttribute;
@class GCSurnamePrefixAttribute;
@class GCTempleAttribute;
@class GCTextAttribute;
@class GCTitleAttribute;
@class GCTypeDescriptionAttribute;
@class GCUserReferenceNumberAttribute;
@class GCVersionAttribute;
@class GCWifeRelationship;

#pragma mark Class definitions

/**
 Autogenerated GCAbbreviationAttribute class.
*/
@interface GCAbbreviationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for abbreviation
 
*/
+(GCAbbreviationAttribute *)abbreviation;
/** Autogenerated convenience constructor for abbreviation
 @param value .
*/
+(GCAbbreviationAttribute *)abbreviationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for abbreviation
 @param value .
*/
+(GCAbbreviationAttribute *)abbreviationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCAddressAttribute class.
*/
@interface GCAddressAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for address
 
*/
+(GCAddressAttribute *)address;
/** Autogenerated convenience constructor for address
 @param value .
*/
+(GCAddressAttribute *)addressWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for address
 @param value .
*/
+(GCAddressAttribute *)addressWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for addressLine1. .
@property GCAddressLine1Attribute *addressLine1;
/// Autogenerated accessors for addressLine2. .
@property GCAddressLine2Attribute *addressLine2;
/// Autogenerated accessors for city. .
@property GCCityAttribute *city;
/// Autogenerated accessors for state. .
@property GCStateAttribute *state;
/// Autogenerated accessors for postalCode. .
@property GCPostalCodeAttribute *postalCode;
/// Autogenerated accessors for country. .
@property GCCountryAttribute *country;

@end

/**
 Autogenerated GCAddressLine1Attribute class.
*/
@interface GCAddressLine1Attribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for addressLine1
 
*/
+(GCAddressLine1Attribute *)addressLine1;
/** Autogenerated convenience constructor for addressLine1
 @param value .
*/
+(GCAddressLine1Attribute *)addressLine1WithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for addressLine1
 @param value .
*/
+(GCAddressLine1Attribute *)addressLine1WithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCAddressLine2Attribute class.
*/
@interface GCAddressLine2Attribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for addressLine2
 
*/
+(GCAddressLine2Attribute *)addressLine2;
/** Autogenerated convenience constructor for addressLine2
 @param value .
*/
+(GCAddressLine2Attribute *)addressLine2WithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for addressLine2
 @param value .
*/
+(GCAddressLine2Attribute *)addressLine2WithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCAdoptionAttribute class.
*/
@interface GCAdoptionAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for adoption
 
*/
+(GCAdoptionAttribute *)adoption;
/** Autogenerated convenience constructor for adoption
 @param value .
*/
+(GCAdoptionAttribute *)adoptionWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for adoption
 @param value .
*/
+(GCAdoptionAttribute *)adoptionWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for childInFamily. .
@property GCChildInFamilyRelationship *childInFamily;

@end

/**
 Autogenerated GCAdultChristeningAttribute class.
*/
@interface GCAdultChristeningAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for adultChristening
 
*/
+(GCAdultChristeningAttribute *)adultChristening;
/** Autogenerated convenience constructor for adultChristening
 @param value .
*/
+(GCAdultChristeningAttribute *)adultChristeningWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for adultChristening
 @param value .
*/
+(GCAdultChristeningAttribute *)adultChristeningWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCAgeAttribute class.
*/
@interface GCAgeAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for age
 
*/
+(GCAgeAttribute *)age;
/** Autogenerated convenience constructor for age
 @param value .
*/
+(GCAgeAttribute *)ageWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for age
 @param value .
*/
+(GCAgeAttribute *)ageWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCAliasRelationship class.
*/
@interface GCAliasRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for alias
 
*/
+(GCAliasRelationship *)alias;
/** Autogenerated convenience constructor for alias
 @param target .
*/
+(GCAliasRelationship *)aliasWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCAncestorInterestRelationship class.
*/
@interface GCAncestorInterestRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for ancestorInterest
 
*/
+(GCAncestorInterestRelationship *)ancestorInterest;
/** Autogenerated convenience constructor for ancestorInterest
 @param target .
*/
+(GCAncestorInterestRelationship *)ancestorInterestWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCAncestralFileNumberAttribute class.
*/
@interface GCAncestralFileNumberAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for ancestralFileNumber
 
*/
+(GCAncestralFileNumberAttribute *)ancestralFileNumber;
/** Autogenerated convenience constructor for ancestralFileNumber
 @param value .
*/
+(GCAncestralFileNumberAttribute *)ancestralFileNumberWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for ancestralFileNumber
 @param value .
*/
+(GCAncestralFileNumberAttribute *)ancestralFileNumberWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCAnnulmentAttribute class.
*/
@interface GCAnnulmentAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for annulment
 
*/
+(GCAnnulmentAttribute *)annulment;
/** Autogenerated convenience constructor for annulment
 @param value .
*/
+(GCAnnulmentAttribute *)annulmentWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for annulment
 @param value .
*/
+(GCAnnulmentAttribute *)annulmentWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCAssociationRelationship class.
*/
@interface GCAssociationRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for association
 
*/
+(GCAssociationRelationship *)association;
/** Autogenerated convenience constructor for association
 @param target .
*/
+(GCAssociationRelationship *)associationWithTarget:(GCEntity *)target;

// Properties:
/// Autogenerated accessors for typeDescription.  //  NB: required property.
@property GCTypeDescriptionAttribute *typeDescription; //  NB: required property
/// Autogenerated accessors for relationshipDescriptor.  //  NB: required property.
@property GCRelationshipDescriptorAttribute *relationshipDescriptor; //  NB: required property
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute
/// Autogenerated accessors for sources. .
@property NSMutableArray *sources;
/// Autogenerated accessors for sourceCitations.  // array of GCSourceCitationRelationship.
@property NSMutableArray *sourceCitations; // array of GCSourceCitationRelationship
/// Autogenerated accessors for sourceEmbeddeds.  // array of GCSourceEmbeddedAttribute.
@property NSMutableArray *sourceEmbeddeds; // array of GCSourceEmbeddedAttribute

@end

/**
 Autogenerated GCAuthorAttribute class.
*/
@interface GCAuthorAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for author
 
*/
+(GCAuthorAttribute *)author;
/** Autogenerated convenience constructor for author
 @param value .
*/
+(GCAuthorAttribute *)authorWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for author
 @param value .
*/
+(GCAuthorAttribute *)authorWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCBaptismAttribute class.
*/
@interface GCBaptismAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for baptism
 
*/
+(GCBaptismAttribute *)baptism;
/** Autogenerated convenience constructor for baptism
 @param value .
*/
+(GCBaptismAttribute *)baptismWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for baptism
 @param value .
*/
+(GCBaptismAttribute *)baptismWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCBarMitzvahAttribute class.
*/
@interface GCBarMitzvahAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for barMitzvah
 
*/
+(GCBarMitzvahAttribute *)barMitzvah;
/** Autogenerated convenience constructor for barMitzvah
 @param value .
*/
+(GCBarMitzvahAttribute *)barMitzvahWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for barMitzvah
 @param value .
*/
+(GCBarMitzvahAttribute *)barMitzvahWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCBasMitzvahAttribute class.
*/
@interface GCBasMitzvahAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for basMitzvah
 
*/
+(GCBasMitzvahAttribute *)basMitzvah;
/** Autogenerated convenience constructor for basMitzvah
 @param value .
*/
+(GCBasMitzvahAttribute *)basMitzvahWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for basMitzvah
 @param value .
*/
+(GCBasMitzvahAttribute *)basMitzvahWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCBinaryObjectAttribute class.
*/
@interface GCBinaryObjectAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for binaryObject
 
*/
+(GCBinaryObjectAttribute *)binaryObject;
/** Autogenerated convenience constructor for binaryObject
 @param value .
*/
+(GCBinaryObjectAttribute *)binaryObjectWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for binaryObject
 @param value .
*/
+(GCBinaryObjectAttribute *)binaryObjectWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCBirthAttribute class.
*/
@interface GCBirthAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for birth
 
*/
+(GCBirthAttribute *)birth;
/** Autogenerated convenience constructor for birth
 @param value .
*/
+(GCBirthAttribute *)birthWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for birth
 @param value .
*/
+(GCBirthAttribute *)birthWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for childInFamily. .
@property GCChildInFamilyRelationship *childInFamily;

@end

/**
 Autogenerated GCBlessingAttribute class.
*/
@interface GCBlessingAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for blessing
 
*/
+(GCBlessingAttribute *)blessing;
/** Autogenerated convenience constructor for blessing
 @param value .
*/
+(GCBlessingAttribute *)blessingWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for blessing
 @param value .
*/
+(GCBlessingAttribute *)blessingWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCBurialAttribute class.
*/
@interface GCBurialAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for burial
 
*/
+(GCBurialAttribute *)burial;
/** Autogenerated convenience constructor for burial
 @param value .
*/
+(GCBurialAttribute *)burialWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for burial
 @param value .
*/
+(GCBurialAttribute *)burialWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCCallNumberAttribute class.
*/
@interface GCCallNumberAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for callNumber
 
*/
+(GCCallNumberAttribute *)callNumber;
/** Autogenerated convenience constructor for callNumber
 @param value .
*/
+(GCCallNumberAttribute *)callNumberWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for callNumber
 @param value .
*/
+(GCCallNumberAttribute *)callNumberWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCCasteAttribute class.
*/
@interface GCCasteAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for caste
 
*/
+(GCCasteAttribute *)caste;
/** Autogenerated convenience constructor for caste
 @param value .
*/
+(GCCasteAttribute *)casteWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for caste
 @param value .
*/
+(GCCasteAttribute *)casteWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCCauseAttribute class.
*/
@interface GCCauseAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for cause
 
*/
+(GCCauseAttribute *)cause;
/** Autogenerated convenience constructor for cause
 @param value .
*/
+(GCCauseAttribute *)causeWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for cause
 @param value .
*/
+(GCCauseAttribute *)causeWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCCensusAttribute class.
*/
@interface GCCensusAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for census
 
*/
+(GCCensusAttribute *)census;
/** Autogenerated convenience constructor for census
 @param value .
*/
+(GCCensusAttribute *)censusWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for census
 @param value .
*/
+(GCCensusAttribute *)censusWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCCharacterSetAttribute class.
*/
@interface GCCharacterSetAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for characterSet
 
*/
+(GCCharacterSetAttribute *)characterSet;
/** Autogenerated convenience constructor for characterSet
 @param value .
*/
+(GCCharacterSetAttribute *)characterSetWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for characterSet
 @param value .
*/
+(GCCharacterSetAttribute *)characterSetWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for version. .
@property GCVersionAttribute *version;

@end

/**
 Autogenerated GCChildRelationship class.
*/
@interface GCChildRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for child
 
*/
+(GCChildRelationship *)child;
/** Autogenerated convenience constructor for child
 @param target .
*/
+(GCChildRelationship *)childWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCChildInFamilyRelationship class.
*/
@interface GCChildInFamilyRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for childInFamily
 
*/
+(GCChildInFamilyRelationship *)childInFamily;
/** Autogenerated convenience constructor for childInFamily
 @param target .
*/
+(GCChildInFamilyRelationship *)childInFamilyWithTarget:(GCEntity *)target;

// Properties:
/// Autogenerated accessors for pedigree. .
@property GCPedigreeAttribute *pedigree;

@end

/**
 Autogenerated GCChristeningAttribute class.
*/
@interface GCChristeningAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for christening
 
*/
+(GCChristeningAttribute *)christening;
/** Autogenerated convenience constructor for christening
 @param value .
*/
+(GCChristeningAttribute *)christeningWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for christening
 @param value .
*/
+(GCChristeningAttribute *)christeningWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for childInFamily. .
@property GCChildInFamilyRelationship *childInFamily;

@end

/**
 Autogenerated GCCityAttribute class.
*/
@interface GCCityAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for city
 
*/
+(GCCityAttribute *)city;
/** Autogenerated convenience constructor for city
 @param value .
*/
+(GCCityAttribute *)cityWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for city
 @param value .
*/
+(GCCityAttribute *)cityWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCConfirmationAttribute class.
*/
@interface GCConfirmationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for confirmation
 
*/
+(GCConfirmationAttribute *)confirmation;
/** Autogenerated convenience constructor for confirmation
 @param value .
*/
+(GCConfirmationAttribute *)confirmationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for confirmation
 @param value .
*/
+(GCConfirmationAttribute *)confirmationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCCopyrightAttribute class.
*/
@interface GCCopyrightAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for copyright
 
*/
+(GCCopyrightAttribute *)copyright;
/** Autogenerated convenience constructor for copyright
 @param value .
*/
+(GCCopyrightAttribute *)copyrightWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for copyright
 @param value .
*/
+(GCCopyrightAttribute *)copyrightWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCCorporationAttribute class.
*/
@interface GCCorporationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for corporation
 
*/
+(GCCorporationAttribute *)corporation;
/** Autogenerated convenience constructor for corporation
 @param value .
*/
+(GCCorporationAttribute *)corporationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for corporation
 @param value .
*/
+(GCCorporationAttribute *)corporationWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for address. .
@property GCAddressAttribute *address;
/// Autogenerated accessors for phoneNumber. .
@property GCPhoneNumberAttribute *phoneNumber;

@end

/**
 Autogenerated GCCountryAttribute class.
*/
@interface GCCountryAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for country
 
*/
+(GCCountryAttribute *)country;
/** Autogenerated convenience constructor for country
 @param value .
*/
+(GCCountryAttribute *)countryWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for country
 @param value .
*/
+(GCCountryAttribute *)countryWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCCremationAttribute class.
*/
@interface GCCremationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for cremation
 
*/
+(GCCremationAttribute *)cremation;
/** Autogenerated convenience constructor for cremation
 @param value .
*/
+(GCCremationAttribute *)cremationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for cremation
 @param value .
*/
+(GCCremationAttribute *)cremationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCCustomEventAttribute class.
*/
@interface GCCustomEventAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for customEvent
 
*/
+(GCCustomEventAttribute *)customEvent;
/** Autogenerated convenience constructor for customEvent
 @param value .
*/
+(GCCustomEventAttribute *)customEventWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for customEvent
 @param value .
*/
+(GCCustomEventAttribute *)customEventWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCDataAttribute class.
*/
@interface GCDataAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for data
 
*/
+(GCDataAttribute *)data;
/** Autogenerated convenience constructor for data
 @param value .
*/
+(GCDataAttribute *)dataWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for data
 @param value .
*/
+(GCDataAttribute *)dataWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for date. .
@property GCDateAttribute *date;
/// Autogenerated accessors for texts.  // array of GCTextAttribute.
@property NSMutableArray *texts; // array of GCTextAttribute

@end

/**
 Autogenerated GCDateAttribute class.
*/
@interface GCDateAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for date
 
*/
+(GCDateAttribute *)date;
/** Autogenerated convenience constructor for date
 @param value .
*/
+(GCDateAttribute *)dateWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for date
 @param value .
*/
+(GCDateAttribute *)dateWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCDeathAttribute class.
*/
@interface GCDeathAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for death
 
*/
+(GCDeathAttribute *)death;
/** Autogenerated convenience constructor for death
 @param value .
*/
+(GCDeathAttribute *)deathWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for death
 @param value .
*/
+(GCDeathAttribute *)deathWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCDescendantInterestRelationship class.
*/
@interface GCDescendantInterestRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for descendantInterest
 
*/
+(GCDescendantInterestRelationship *)descendantInterest;
/** Autogenerated convenience constructor for descendantInterest
 @param target .
*/
+(GCDescendantInterestRelationship *)descendantInterestWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCDestinationAttribute class.
*/
@interface GCDestinationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for destination
 
*/
+(GCDestinationAttribute *)destination;
/** Autogenerated convenience constructor for destination
 @param value .
*/
+(GCDestinationAttribute *)destinationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for destination
 @param value .
*/
+(GCDestinationAttribute *)destinationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCDivorceAttribute class.
*/
@interface GCDivorceAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for divorce
 
*/
+(GCDivorceAttribute *)divorce;
/** Autogenerated convenience constructor for divorce
 @param value .
*/
+(GCDivorceAttribute *)divorceWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for divorce
 @param value .
*/
+(GCDivorceAttribute *)divorceWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCDivorceFiledAttribute class.
*/
@interface GCDivorceFiledAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for divorceFiled
 
*/
+(GCDivorceFiledAttribute *)divorceFiled;
/** Autogenerated convenience constructor for divorceFiled
 @param value .
*/
+(GCDivorceFiledAttribute *)divorceFiledWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for divorceFiled
 @param value .
*/
+(GCDivorceFiledAttribute *)divorceFiledWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCEducationAttribute class.
*/
@interface GCEducationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for education
 
*/
+(GCEducationAttribute *)education;
/** Autogenerated convenience constructor for education
 @param value .
*/
+(GCEducationAttribute *)educationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for education
 @param value .
*/
+(GCEducationAttribute *)educationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCEmigrationAttribute class.
*/
@interface GCEmigrationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for emigration
 
*/
+(GCEmigrationAttribute *)emigration;
/** Autogenerated convenience constructor for emigration
 @param value .
*/
+(GCEmigrationAttribute *)emigrationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for emigration
 @param value .
*/
+(GCEmigrationAttribute *)emigrationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCEngagementAttribute class.
*/
@interface GCEngagementAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for engagement
 
*/
+(GCEngagementAttribute *)engagement;
/** Autogenerated convenience constructor for engagement
 @param value .
*/
+(GCEngagementAttribute *)engagementWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for engagement
 @param value .
*/
+(GCEngagementAttribute *)engagementWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCEventsRecordedAttribute class.
*/
@interface GCEventsRecordedAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for eventsRecorded
 
*/
+(GCEventsRecordedAttribute *)eventsRecorded;
/** Autogenerated convenience constructor for eventsRecorded
 @param value .
*/
+(GCEventsRecordedAttribute *)eventsRecordedWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for eventsRecorded
 @param value .
*/
+(GCEventsRecordedAttribute *)eventsRecordedWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for date. .
@property GCDateAttribute *date;
/// Autogenerated accessors for place. .
@property GCPlaceAttribute *place;

@end

/**
 Autogenerated GCFamilyEntity class.
*/
@interface GCFamilyEntity : GCEntity

// Methods:
/** Autogenerated convenience constructor for family
 @param context .
*/
+(GCFamilyEntity *)familyInContext:(GCContext *)context;

// Properties:
/// Autogenerated accessors for familyEvents. .
@property NSMutableArray *familyEvents;
/// Autogenerated accessors for annulments.  // array of GCAnnulmentAttribute.
@property NSMutableArray *annulments; // array of GCAnnulmentAttribute
/// Autogenerated accessors for censuses.  // array of GCCensusAttribute.
@property NSMutableArray *censuses; // array of GCCensusAttribute
/// Autogenerated accessors for divorces.  // array of GCDivorceAttribute.
@property NSMutableArray *divorces; // array of GCDivorceAttribute
/// Autogenerated accessors for divorceFileds.  // array of GCDivorceFiledAttribute.
@property NSMutableArray *divorceFileds; // array of GCDivorceFiledAttribute
/// Autogenerated accessors for engagements.  // array of GCEngagementAttribute.
@property NSMutableArray *engagements; // array of GCEngagementAttribute
/// Autogenerated accessors for marriages.  // array of GCMarriageAttribute.
@property NSMutableArray *marriages; // array of GCMarriageAttribute
/// Autogenerated accessors for marriageBanns.  // array of GCMarriageBannAttribute.
@property NSMutableArray *marriageBanns; // array of GCMarriageBannAttribute
/// Autogenerated accessors for marriageContracts.  // array of GCMarriageContractAttribute.
@property NSMutableArray *marriageContracts; // array of GCMarriageContractAttribute
/// Autogenerated accessors for marriageLicenses.  // array of GCMarriageLicenseAttribute.
@property NSMutableArray *marriageLicenses; // array of GCMarriageLicenseAttribute
/// Autogenerated accessors for marriageSettlements.  // array of GCMarriageSettlementAttribute.
@property NSMutableArray *marriageSettlements; // array of GCMarriageSettlementAttribute
/// Autogenerated accessors for customEvents.  // array of GCCustomEventAttribute.
@property NSMutableArray *customEvents; // array of GCCustomEventAttribute
/// Autogenerated accessors for husband. .
@property GCHusbandRelationship *husband;
/// Autogenerated accessors for wife. .
@property GCWifeRelationship *wife;
/// Autogenerated accessors for children.  // array of GCChildRelationship.
@property NSMutableArray *children; // array of GCChildRelationship
/// Autogenerated accessors for numberOfChildren. .
@property GCNumberOfChildrenAttribute *numberOfChildren;
/// Autogenerated accessors for submissionReferences.  // array of GCSubmissionReferenceRelationship.
@property NSMutableArray *submissionReferences; // array of GCSubmissionReferenceRelationship
/// Autogenerated accessors for sources. .
@property NSMutableArray *sources;
/// Autogenerated accessors for sourceCitations.  // array of GCSourceCitationRelationship.
@property NSMutableArray *sourceCitations; // array of GCSourceCitationRelationship
/// Autogenerated accessors for sourceEmbeddeds.  // array of GCSourceEmbeddedAttribute.
@property NSMutableArray *sourceEmbeddeds; // array of GCSourceEmbeddedAttribute
/// Autogenerated accessors for multimedias. .
@property NSMutableArray *multimedias;
/// Autogenerated accessors for multimediaReferences.  // array of GCMultimediaReferenceRelationship.
@property NSMutableArray *multimediaReferences; // array of GCMultimediaReferenceRelationship
/// Autogenerated accessors for multimediaEmbeddeds.  // array of GCMultimediaEmbeddedAttribute.
@property NSMutableArray *multimediaEmbeddeds; // array of GCMultimediaEmbeddedAttribute
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute
/// Autogenerated accessors for userReferenceNumbers.  // array of GCUserReferenceNumberAttribute.
@property NSMutableArray *userReferenceNumbers; // array of GCUserReferenceNumberAttribute

@end

/**
 Autogenerated GCFamilyFileAttribute class.
*/
@interface GCFamilyFileAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for familyFile
 
*/
+(GCFamilyFileAttribute *)familyFile;
/** Autogenerated convenience constructor for familyFile
 @param value .
*/
+(GCFamilyFileAttribute *)familyFileWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for familyFile
 @param value .
*/
+(GCFamilyFileAttribute *)familyFileWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCFileAttribute class.
*/
@interface GCFileAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for file
 
*/
+(GCFileAttribute *)file;
/** Autogenerated convenience constructor for file
 @param value .
*/
+(GCFileAttribute *)fileWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for file
 @param value .
*/
+(GCFileAttribute *)fileWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCFirstCommunionAttribute class.
*/
@interface GCFirstCommunionAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for firstCommunion
 
*/
+(GCFirstCommunionAttribute *)firstCommunion;
/** Autogenerated convenience constructor for firstCommunion
 @param value .
*/
+(GCFirstCommunionAttribute *)firstCommunionWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for firstCommunion
 @param value .
*/
+(GCFirstCommunionAttribute *)firstCommunionWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCFormatAttribute class.
*/
@interface GCFormatAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for format
 
*/
+(GCFormatAttribute *)format;
/** Autogenerated convenience constructor for format
 @param value .
*/
+(GCFormatAttribute *)formatWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for format
 @param value .
*/
+(GCFormatAttribute *)formatWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCGedcomAttribute class.
*/
@interface GCGedcomAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for gedcom
 
*/
+(GCGedcomAttribute *)gedcom;
/** Autogenerated convenience constructor for gedcom
 @param value .
*/
+(GCGedcomAttribute *)gedcomWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for gedcom
 @param value .
*/
+(GCGedcomAttribute *)gedcomWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for version.  //  NB: required property.
@property GCVersionAttribute *version; //  NB: required property
/// Autogenerated accessors for format.  //  NB: required property.
@property GCFormatAttribute *format; //  NB: required property

@end

/**
 Autogenerated GCGenerationsOfAncestorsAttribute class.
*/
@interface GCGenerationsOfAncestorsAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for generationsOfAncestors
 
*/
+(GCGenerationsOfAncestorsAttribute *)generationsOfAncestors;
/** Autogenerated convenience constructor for generationsOfAncestors
 @param value .
*/
+(GCGenerationsOfAncestorsAttribute *)generationsOfAncestorsWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for generationsOfAncestors
 @param value .
*/
+(GCGenerationsOfAncestorsAttribute *)generationsOfAncestorsWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCGenerationsOfDescendantsAttribute class.
*/
@interface GCGenerationsOfDescendantsAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for generationsOfDescendants
 
*/
+(GCGenerationsOfDescendantsAttribute *)generationsOfDescendants;
/** Autogenerated convenience constructor for generationsOfDescendants
 @param value .
*/
+(GCGenerationsOfDescendantsAttribute *)generationsOfDescendantsWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for generationsOfDescendants
 @param value .
*/
+(GCGenerationsOfDescendantsAttribute *)generationsOfDescendantsWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCGivenNameAttribute class.
*/
@interface GCGivenNameAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for givenName
 
*/
+(GCGivenNameAttribute *)givenName;
/** Autogenerated convenience constructor for givenName
 @param value .
*/
+(GCGivenNameAttribute *)givenNameWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for givenName
 @param value .
*/
+(GCGivenNameAttribute *)givenNameWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCGraduationAttribute class.
*/
@interface GCGraduationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for graduation
 
*/
+(GCGraduationAttribute *)graduation;
/** Autogenerated convenience constructor for graduation
 @param value .
*/
+(GCGraduationAttribute *)graduationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for graduation
 @param value .
*/
+(GCGraduationAttribute *)graduationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCHeaderSourceAttribute class.
*/
@interface GCHeaderSourceAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for headerSource
 
*/
+(GCHeaderSourceAttribute *)headerSource;
/** Autogenerated convenience constructor for headerSource
 @param value .
*/
+(GCHeaderSourceAttribute *)headerSourceWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for headerSource
 @param value .
*/
+(GCHeaderSourceAttribute *)headerSourceWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for version. .
@property GCVersionAttribute *version;
/// Autogenerated accessors for name. .
@property GCNameAttribute *name;
/// Autogenerated accessors for corporation. .
@property GCCorporationAttribute *corporation;
/// Autogenerated accessors for data. .
@property GCDataAttribute *data;

@end

/**
 Autogenerated GCHusbandRelationship class.
*/
@interface GCHusbandRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for husband
 
*/
+(GCHusbandRelationship *)husband;
/** Autogenerated convenience constructor for husband
 @param target .
*/
+(GCHusbandRelationship *)husbandWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCIdentNumberAttribute class.
*/
@interface GCIdentNumberAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for identNumber
 
*/
+(GCIdentNumberAttribute *)identNumber;
/** Autogenerated convenience constructor for identNumber
 @param value .
*/
+(GCIdentNumberAttribute *)identNumberWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for identNumber
 @param value .
*/
+(GCIdentNumberAttribute *)identNumberWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCImmigrationAttribute class.
*/
@interface GCImmigrationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for immigration
 
*/
+(GCImmigrationAttribute *)immigration;
/** Autogenerated convenience constructor for immigration
 @param value .
*/
+(GCImmigrationAttribute *)immigrationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for immigration
 @param value .
*/
+(GCImmigrationAttribute *)immigrationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCIndividualEntity class.
*/
@interface GCIndividualEntity : GCEntity

// Methods:
/** Autogenerated convenience constructor for individual
 @param context .
*/
+(GCIndividualEntity *)individualInContext:(GCContext *)context;

// Properties:
/// Autogenerated accessors for restrictionNotice. .
@property GCRestrictionNoticeAttribute *restrictionNotice;
/// Autogenerated accessors for personalNames.  // array of GCPersonalNameAttribute.
@property NSMutableArray *personalNames; // array of GCPersonalNameAttribute
/// Autogenerated accessors for sex. .
@property GCSexAttribute *sex;
/// Autogenerated accessors for individualEvents. .
@property NSMutableArray *individualEvents;
/// Autogenerated accessors for births.  // array of GCBirthAttribute.
@property NSMutableArray *births; // array of GCBirthAttribute
/// Autogenerated accessors for christenings.  // array of GCChristeningAttribute.
@property NSMutableArray *christenings; // array of GCChristeningAttribute
/// Autogenerated accessors for deaths.  // array of GCDeathAttribute.
@property NSMutableArray *deaths; // array of GCDeathAttribute
/// Autogenerated accessors for burials.  // array of GCBurialAttribute.
@property NSMutableArray *burials; // array of GCBurialAttribute
/// Autogenerated accessors for cremations.  // array of GCCremationAttribute.
@property NSMutableArray *cremations; // array of GCCremationAttribute
/// Autogenerated accessors for adoptions.  // array of GCAdoptionAttribute.
@property NSMutableArray *adoptions; // array of GCAdoptionAttribute
/// Autogenerated accessors for baptisms.  // array of GCBaptismAttribute.
@property NSMutableArray *baptisms; // array of GCBaptismAttribute
/// Autogenerated accessors for barMitzvahs.  // array of GCBarMitzvahAttribute.
@property NSMutableArray *barMitzvahs; // array of GCBarMitzvahAttribute
/// Autogenerated accessors for basMitzvahs.  // array of GCBasMitzvahAttribute.
@property NSMutableArray *basMitzvahs; // array of GCBasMitzvahAttribute
/// Autogenerated accessors for blessings.  // array of GCBlessingAttribute.
@property NSMutableArray *blessings; // array of GCBlessingAttribute
/// Autogenerated accessors for adultChristenings.  // array of GCAdultChristeningAttribute.
@property NSMutableArray *adultChristenings; // array of GCAdultChristeningAttribute
/// Autogenerated accessors for confirmations.  // array of GCConfirmationAttribute.
@property NSMutableArray *confirmations; // array of GCConfirmationAttribute
/// Autogenerated accessors for firstCommunions.  // array of GCFirstCommunionAttribute.
@property NSMutableArray *firstCommunions; // array of GCFirstCommunionAttribute
/// Autogenerated accessors for ordinances.  // array of GCOrdinanceAttribute.
@property NSMutableArray *ordinances; // array of GCOrdinanceAttribute
/// Autogenerated accessors for naturalizations.  // array of GCNaturalizationAttribute.
@property NSMutableArray *naturalizations; // array of GCNaturalizationAttribute
/// Autogenerated accessors for emigrations.  // array of GCEmigrationAttribute.
@property NSMutableArray *emigrations; // array of GCEmigrationAttribute
/// Autogenerated accessors for immigrations.  // array of GCImmigrationAttribute.
@property NSMutableArray *immigrations; // array of GCImmigrationAttribute
/// Autogenerated accessors for censuses.  // array of GCCensusAttribute.
@property NSMutableArray *censuses; // array of GCCensusAttribute
/// Autogenerated accessors for probates.  // array of GCProbateAttribute.
@property NSMutableArray *probates; // array of GCProbateAttribute
/// Autogenerated accessors for wills.  // array of GCWillAttribute.
@property NSMutableArray *wills; // array of GCWillAttribute
/// Autogenerated accessors for graduations.  // array of GCGraduationAttribute.
@property NSMutableArray *graduations; // array of GCGraduationAttribute
/// Autogenerated accessors for retirements.  // array of GCRetirementAttribute.
@property NSMutableArray *retirements; // array of GCRetirementAttribute
/// Autogenerated accessors for customEvents.  // array of GCCustomEventAttribute.
@property NSMutableArray *customEvents; // array of GCCustomEventAttribute
/// Autogenerated accessors for individualAttributes. .
@property NSMutableArray *individualAttributes;
/// Autogenerated accessors for castes.  // array of GCCasteAttribute.
@property NSMutableArray *castes; // array of GCCasteAttribute
/// Autogenerated accessors for generationsOfDescendantss.  // array of GCGenerationsOfDescendantsAttribute.
@property NSMutableArray *generationsOfDescendantss; // array of GCGenerationsOfDescendantsAttribute
/// Autogenerated accessors for educations.  // array of GCEducationAttribute.
@property NSMutableArray *educations; // array of GCEducationAttribute
/// Autogenerated accessors for identNumbers.  // array of GCIdentNumberAttribute.
@property NSMutableArray *identNumbers; // array of GCIdentNumberAttribute
/// Autogenerated accessors for nationalities.  // array of GCNationalityAttribute.
@property NSMutableArray *nationalities; // array of GCNationalityAttribute
/// Autogenerated accessors for numberOfChildrens.  // array of GCNumberOfChildrenAttribute.
@property NSMutableArray *numberOfChildrens; // array of GCNumberOfChildrenAttribute
/// Autogenerated accessors for numberOfMarriagess.  // array of GCNumberOfMarriagesAttribute.
@property NSMutableArray *numberOfMarriagess; // array of GCNumberOfMarriagesAttribute
/// Autogenerated accessors for occupations.  // array of GCOccupationAttribute.
@property NSMutableArray *occupations; // array of GCOccupationAttribute
/// Autogenerated accessors for propertyOwneds.  // array of GCPropertyOwnedAttribute.
@property NSMutableArray *propertyOwneds; // array of GCPropertyOwnedAttribute
/// Autogenerated accessors for religions.  // array of GCReligionAttribute.
@property NSMutableArray *religions; // array of GCReligionAttribute
/// Autogenerated accessors for residences.  // array of GCResidenceAttribute.
@property NSMutableArray *residences; // array of GCResidenceAttribute
/// Autogenerated accessors for socialSecurityNumbers.  // array of GCSocialSecurityNumberAttribute.
@property NSMutableArray *socialSecurityNumbers; // array of GCSocialSecurityNumberAttribute
/// Autogenerated accessors for titles.  // array of GCTitleAttribute.
@property NSMutableArray *titles; // array of GCTitleAttribute
/// Autogenerated accessors for individualLDSOrdinances. .
@property NSMutableArray *individualLDSOrdinances;
/// Autogenerated accessors for lDSBaptisms.  // array of GCLDSBaptismAttribute.
@property NSMutableArray *lDSBaptisms; // array of GCLDSBaptismAttribute
/// Autogenerated accessors for lDSConfirmations.  // array of GCLDSConfirmationAttribute.
@property NSMutableArray *lDSConfirmations; // array of GCLDSConfirmationAttribute
/// Autogenerated accessors for lDSEndowments.  // array of GCLDSEndowmentAttribute.
@property NSMutableArray *lDSEndowments; // array of GCLDSEndowmentAttribute
/// Autogenerated accessors for lDSSealingChilds.  // array of GCLDSSealingChildAttribute.
@property NSMutableArray *lDSSealingChilds; // array of GCLDSSealingChildAttribute
/// Autogenerated accessors for childInFamilies.  // array of GCChildInFamilyRelationship.
@property NSMutableArray *childInFamilies; // array of GCChildInFamilyRelationship
/// Autogenerated accessors for spouseInFamilies.  // array of GCSpouseInFamilyRelationship.
@property NSMutableArray *spouseInFamilies; // array of GCSpouseInFamilyRelationship
/// Autogenerated accessors for submissionReferences.  // array of GCSubmissionReferenceRelationship.
@property NSMutableArray *submissionReferences; // array of GCSubmissionReferenceRelationship
/// Autogenerated accessors for associations.  // array of GCAssociationRelationship.
@property NSMutableArray *associations; // array of GCAssociationRelationship
/// Autogenerated accessors for aliases.  // array of GCAliasRelationship.
@property NSMutableArray *aliases; // array of GCAliasRelationship
/// Autogenerated accessors for ancestorInterests.  // array of GCAncestorInterestRelationship.
@property NSMutableArray *ancestorInterests; // array of GCAncestorInterestRelationship
/// Autogenerated accessors for descendantInterests.  // array of GCDescendantInterestRelationship.
@property NSMutableArray *descendantInterests; // array of GCDescendantInterestRelationship
/// Autogenerated accessors for sources. .
@property NSMutableArray *sources;
/// Autogenerated accessors for sourceCitations.  // array of GCSourceCitationRelationship.
@property NSMutableArray *sourceCitations; // array of GCSourceCitationRelationship
/// Autogenerated accessors for sourceEmbeddeds.  // array of GCSourceEmbeddedAttribute.
@property NSMutableArray *sourceEmbeddeds; // array of GCSourceEmbeddedAttribute
/// Autogenerated accessors for multimedias. .
@property NSMutableArray *multimedias;
/// Autogenerated accessors for multimediaReferences.  // array of GCMultimediaReferenceRelationship.
@property NSMutableArray *multimediaReferences; // array of GCMultimediaReferenceRelationship
/// Autogenerated accessors for multimediaEmbeddeds.  // array of GCMultimediaEmbeddedAttribute.
@property NSMutableArray *multimediaEmbeddeds; // array of GCMultimediaEmbeddedAttribute
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute
/// Autogenerated accessors for userReferenceNumbers.  // array of GCUserReferenceNumberAttribute.
@property NSMutableArray *userReferenceNumbers; // array of GCUserReferenceNumberAttribute

@end

/**
 Autogenerated GCLDSBaptismAttribute class.
*/
@interface GCLDSBaptismAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for lDSBaptism
 
*/
+(GCLDSBaptismAttribute *)lDSBaptism;
/** Autogenerated convenience constructor for lDSBaptism
 @param value .
*/
+(GCLDSBaptismAttribute *)lDSBaptismWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for lDSBaptism
 @param value .
*/
+(GCLDSBaptismAttribute *)lDSBaptismWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCLDSConfirmationAttribute class.
*/
@interface GCLDSConfirmationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for lDSConfirmation
 
*/
+(GCLDSConfirmationAttribute *)lDSConfirmation;
/** Autogenerated convenience constructor for lDSConfirmation
 @param value .
*/
+(GCLDSConfirmationAttribute *)lDSConfirmationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for lDSConfirmation
 @param value .
*/
+(GCLDSConfirmationAttribute *)lDSConfirmationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCLDSEndowmentAttribute class.
*/
@interface GCLDSEndowmentAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for lDSEndowment
 
*/
+(GCLDSEndowmentAttribute *)lDSEndowment;
/** Autogenerated convenience constructor for lDSEndowment
 @param value .
*/
+(GCLDSEndowmentAttribute *)lDSEndowmentWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for lDSEndowment
 @param value .
*/
+(GCLDSEndowmentAttribute *)lDSEndowmentWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCLDSSealingChildAttribute class.
*/
@interface GCLDSSealingChildAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for lDSSealingChild
 
*/
+(GCLDSSealingChildAttribute *)lDSSealingChild;
/** Autogenerated convenience constructor for lDSSealingChild
 @param value .
*/
+(GCLDSSealingChildAttribute *)lDSSealingChildWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for lDSSealingChild
 @param value .
*/
+(GCLDSSealingChildAttribute *)lDSSealingChildWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCLanguageAttribute class.
*/
@interface GCLanguageAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for language
 
*/
+(GCLanguageAttribute *)language;
/** Autogenerated convenience constructor for language
 @param value .
*/
+(GCLanguageAttribute *)languageWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for language
 @param value .
*/
+(GCLanguageAttribute *)languageWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCLegateeAttribute class.
*/
@interface GCLegateeAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for legatee
 
*/
+(GCLegateeAttribute *)legatee;
/** Autogenerated convenience constructor for legatee
 @param value .
*/
+(GCLegateeAttribute *)legateeWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for legatee
 @param value .
*/
+(GCLegateeAttribute *)legateeWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCMarriageAttribute class.
*/
@interface GCMarriageAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for marriage
 
*/
+(GCMarriageAttribute *)marriage;
/** Autogenerated convenience constructor for marriage
 @param value .
*/
+(GCMarriageAttribute *)marriageWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for marriage
 @param value .
*/
+(GCMarriageAttribute *)marriageWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCMarriageBannAttribute class.
*/
@interface GCMarriageBannAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for marriageBann
 
*/
+(GCMarriageBannAttribute *)marriageBann;
/** Autogenerated convenience constructor for marriageBann
 @param value .
*/
+(GCMarriageBannAttribute *)marriageBannWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for marriageBann
 @param value .
*/
+(GCMarriageBannAttribute *)marriageBannWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCMarriageContractAttribute class.
*/
@interface GCMarriageContractAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for marriageContract
 
*/
+(GCMarriageContractAttribute *)marriageContract;
/** Autogenerated convenience constructor for marriageContract
 @param value .
*/
+(GCMarriageContractAttribute *)marriageContractWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for marriageContract
 @param value .
*/
+(GCMarriageContractAttribute *)marriageContractWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCMarriageLicenseAttribute class.
*/
@interface GCMarriageLicenseAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for marriageLicense
 
*/
+(GCMarriageLicenseAttribute *)marriageLicense;
/** Autogenerated convenience constructor for marriageLicense
 @param value .
*/
+(GCMarriageLicenseAttribute *)marriageLicenseWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for marriageLicense
 @param value .
*/
+(GCMarriageLicenseAttribute *)marriageLicenseWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCMarriageSettlementAttribute class.
*/
@interface GCMarriageSettlementAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for marriageSettlement
 
*/
+(GCMarriageSettlementAttribute *)marriageSettlement;
/** Autogenerated convenience constructor for marriageSettlement
 @param value .
*/
+(GCMarriageSettlementAttribute *)marriageSettlementWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for marriageSettlement
 @param value .
*/
+(GCMarriageSettlementAttribute *)marriageSettlementWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCMediaAttribute class.
*/
@interface GCMediaAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for media
 
*/
+(GCMediaAttribute *)media;
/** Autogenerated convenience constructor for media
 @param value .
*/
+(GCMediaAttribute *)mediaWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for media
 @param value .
*/
+(GCMediaAttribute *)mediaWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCMultimediaEntity class.
*/
@interface GCMultimediaEntity : GCEntity

// Methods:
/** Autogenerated convenience constructor for multimedia
 @param context .
*/
+(GCMultimediaEntity *)multimediaInContext:(GCContext *)context;

// Properties:
/// Autogenerated accessors for format.  //  NB: required property.
@property GCFormatAttribute *format; //  NB: required property
/// Autogenerated accessors for title. .
@property GCTitleAttribute *title;
/// Autogenerated accessors for userReferenceNumbers.  // array of GCUserReferenceNumberAttribute.
@property NSMutableArray *userReferenceNumbers; // array of GCUserReferenceNumberAttribute

@end

/**
 Autogenerated GCMultimediaEmbeddedAttribute class.
*/
@interface GCMultimediaEmbeddedAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for multimediaEmbedded
 
*/
+(GCMultimediaEmbeddedAttribute *)multimediaEmbedded;
/** Autogenerated convenience constructor for multimediaEmbedded
 @param value .
*/
+(GCMultimediaEmbeddedAttribute *)multimediaEmbeddedWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for multimediaEmbedded
 @param value .
*/
+(GCMultimediaEmbeddedAttribute *)multimediaEmbeddedWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for format.  //  NB: required property.
@property GCFormatAttribute *format; //  NB: required property
/// Autogenerated accessors for title. .
@property GCTitleAttribute *title;
/// Autogenerated accessors for file. .
@property GCFileAttribute *file;
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute

@end

/**
 Autogenerated GCMultimediaReferenceRelationship class.
*/
@interface GCMultimediaReferenceRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for multimediaReference
 
*/
+(GCMultimediaReferenceRelationship *)multimediaReference;
/** Autogenerated convenience constructor for multimediaReference
 @param target .
*/
+(GCMultimediaReferenceRelationship *)multimediaReferenceWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCNameAttribute class.
*/
@interface GCNameAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for name
 
*/
+(GCNameAttribute *)name;
/** Autogenerated convenience constructor for name
 @param value .
*/
+(GCNameAttribute *)nameWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for name
 @param value .
*/
+(GCNameAttribute *)nameWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCNamePrefixAttribute class.
*/
@interface GCNamePrefixAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for namePrefix
 
*/
+(GCNamePrefixAttribute *)namePrefix;
/** Autogenerated convenience constructor for namePrefix
 @param value .
*/
+(GCNamePrefixAttribute *)namePrefixWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for namePrefix
 @param value .
*/
+(GCNamePrefixAttribute *)namePrefixWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCNameSuffixAttribute class.
*/
@interface GCNameSuffixAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for nameSuffix
 
*/
+(GCNameSuffixAttribute *)nameSuffix;
/** Autogenerated convenience constructor for nameSuffix
 @param value .
*/
+(GCNameSuffixAttribute *)nameSuffixWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for nameSuffix
 @param value .
*/
+(GCNameSuffixAttribute *)nameSuffixWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCNationalityAttribute class.
*/
@interface GCNationalityAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for nationality
 
*/
+(GCNationalityAttribute *)nationality;
/** Autogenerated convenience constructor for nationality
 @param value .
*/
+(GCNationalityAttribute *)nationalityWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for nationality
 @param value .
*/
+(GCNationalityAttribute *)nationalityWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCNaturalizationAttribute class.
*/
@interface GCNaturalizationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for naturalization
 
*/
+(GCNaturalizationAttribute *)naturalization;
/** Autogenerated convenience constructor for naturalization
 @param value .
*/
+(GCNaturalizationAttribute *)naturalizationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for naturalization
 @param value .
*/
+(GCNaturalizationAttribute *)naturalizationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCNicknameAttribute class.
*/
@interface GCNicknameAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for nickname
 
*/
+(GCNicknameAttribute *)nickname;
/** Autogenerated convenience constructor for nickname
 @param value .
*/
+(GCNicknameAttribute *)nicknameWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for nickname
 @param value .
*/
+(GCNicknameAttribute *)nicknameWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCNoteEntity class.
*/
@interface GCNoteEntity : GCEntity

// Methods:
/** Autogenerated convenience constructor for note
 @param context .
*/
+(GCNoteEntity *)noteInContext:(GCContext *)context;

// Properties:
/// Autogenerated accessors for recordIdNumber. .
@property GCRecordIdNumberAttribute *recordIdNumber;
/// Autogenerated accessors for userReferenceNumbers.  // array of GCUserReferenceNumberAttribute.
@property NSMutableArray *userReferenceNumbers; // array of GCUserReferenceNumberAttribute

@end

/**
 Autogenerated GCNoteEmbeddedAttribute class.
*/
@interface GCNoteEmbeddedAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for noteEmbedded
 
*/
+(GCNoteEmbeddedAttribute *)noteEmbedded;
/** Autogenerated convenience constructor for noteEmbedded
 @param value .
*/
+(GCNoteEmbeddedAttribute *)noteEmbeddedWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for noteEmbedded
 @param value .
*/
+(GCNoteEmbeddedAttribute *)noteEmbeddedWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCNoteReferenceRelationship class.
*/
@interface GCNoteReferenceRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for noteReference
 
*/
+(GCNoteReferenceRelationship *)noteReference;
/** Autogenerated convenience constructor for noteReference
 @param target .
*/
+(GCNoteReferenceRelationship *)noteReferenceWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCNumberOfChildrenAttribute class.
*/
@interface GCNumberOfChildrenAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for numberOfChildren
 
*/
+(GCNumberOfChildrenAttribute *)numberOfChildren;
/** Autogenerated convenience constructor for numberOfChildren
 @param value .
*/
+(GCNumberOfChildrenAttribute *)numberOfChildrenWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for numberOfChildren
 @param value .
*/
+(GCNumberOfChildrenAttribute *)numberOfChildrenWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCNumberOfMarriagesAttribute class.
*/
@interface GCNumberOfMarriagesAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for numberOfMarriages
 
*/
+(GCNumberOfMarriagesAttribute *)numberOfMarriages;
/** Autogenerated convenience constructor for numberOfMarriages
 @param value .
*/
+(GCNumberOfMarriagesAttribute *)numberOfMarriagesWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for numberOfMarriages
 @param value .
*/
+(GCNumberOfMarriagesAttribute *)numberOfMarriagesWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCOccupationAttribute class.
*/
@interface GCOccupationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for occupation
 
*/
+(GCOccupationAttribute *)occupation;
/** Autogenerated convenience constructor for occupation
 @param value .
*/
+(GCOccupationAttribute *)occupationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for occupation
 @param value .
*/
+(GCOccupationAttribute *)occupationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCOrdinanceAttribute class.
*/
@interface GCOrdinanceAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for ordinance
 
*/
+(GCOrdinanceAttribute *)ordinance;
/** Autogenerated convenience constructor for ordinance
 @param value .
*/
+(GCOrdinanceAttribute *)ordinanceWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for ordinance
 @param value .
*/
+(GCOrdinanceAttribute *)ordinanceWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCOrdinationAttribute class.
*/
@interface GCOrdinationAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for ordination
 
*/
+(GCOrdinationAttribute *)ordination;
/** Autogenerated convenience constructor for ordination
 @param value .
*/
+(GCOrdinationAttribute *)ordinationWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for ordination
 @param value .
*/
+(GCOrdinationAttribute *)ordinationWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCPageAttribute class.
*/
@interface GCPageAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for page
 
*/
+(GCPageAttribute *)page;
/** Autogenerated convenience constructor for page
 @param value .
*/
+(GCPageAttribute *)pageWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for page
 @param value .
*/
+(GCPageAttribute *)pageWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCPedigreeAttribute class.
*/
@interface GCPedigreeAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for pedigree
 
*/
+(GCPedigreeAttribute *)pedigree;
/** Autogenerated convenience constructor for pedigree
 @param value .
*/
+(GCPedigreeAttribute *)pedigreeWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for pedigree
 @param value .
*/
+(GCPedigreeAttribute *)pedigreeWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCPersonalNameAttribute class.
*/
@interface GCPersonalNameAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for personalName
 
*/
+(GCPersonalNameAttribute *)personalName;
/** Autogenerated convenience constructor for personalName
 @param value .
*/
+(GCPersonalNameAttribute *)personalNameWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for personalName
 @param value .
*/
+(GCPersonalNameAttribute *)personalNameWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for namePrefix. .
@property GCNamePrefixAttribute *namePrefix;
/// Autogenerated accessors for givenName. .
@property GCGivenNameAttribute *givenName;
/// Autogenerated accessors for nickname. .
@property GCNicknameAttribute *nickname;
/// Autogenerated accessors for surnamePrefix. .
@property GCSurnamePrefixAttribute *surnamePrefix;
/// Autogenerated accessors for surname. .
@property GCSurnameAttribute *surname;
/// Autogenerated accessors for nameSuffix. .
@property GCNameSuffixAttribute *nameSuffix;
/// Autogenerated accessors for sources. .
@property NSMutableArray *sources;
/// Autogenerated accessors for sourceCitations.  // array of GCSourceCitationRelationship.
@property NSMutableArray *sourceCitations; // array of GCSourceCitationRelationship
/// Autogenerated accessors for sourceEmbeddeds.  // array of GCSourceEmbeddedAttribute.
@property NSMutableArray *sourceEmbeddeds; // array of GCSourceEmbeddedAttribute
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute

@end

/**
 Autogenerated GCPhoneNumberAttribute class.
*/
@interface GCPhoneNumberAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for phoneNumber
 
*/
+(GCPhoneNumberAttribute *)phoneNumber;
/** Autogenerated convenience constructor for phoneNumber
 @param value .
*/
+(GCPhoneNumberAttribute *)phoneNumberWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for phoneNumber
 @param value .
*/
+(GCPhoneNumberAttribute *)phoneNumberWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCPhysicalDescriptionAttribute class.
*/
@interface GCPhysicalDescriptionAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for physicalDescription
 
*/
+(GCPhysicalDescriptionAttribute *)physicalDescription;
/** Autogenerated convenience constructor for physicalDescription
 @param value .
*/
+(GCPhysicalDescriptionAttribute *)physicalDescriptionWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for physicalDescription
 @param value .
*/
+(GCPhysicalDescriptionAttribute *)physicalDescriptionWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCPlaceAttribute class.
*/
@interface GCPlaceAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for place
 
*/
+(GCPlaceAttribute *)place;
/** Autogenerated convenience constructor for place
 @param value .
*/
+(GCPlaceAttribute *)placeWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for place
 @param value .
*/
+(GCPlaceAttribute *)placeWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCPostalCodeAttribute class.
*/
@interface GCPostalCodeAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for postalCode
 
*/
+(GCPostalCodeAttribute *)postalCode;
/** Autogenerated convenience constructor for postalCode
 @param value .
*/
+(GCPostalCodeAttribute *)postalCodeWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for postalCode
 @param value .
*/
+(GCPostalCodeAttribute *)postalCodeWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCProbateAttribute class.
*/
@interface GCProbateAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for probate
 
*/
+(GCProbateAttribute *)probate;
/** Autogenerated convenience constructor for probate
 @param value .
*/
+(GCProbateAttribute *)probateWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for probate
 @param value .
*/
+(GCProbateAttribute *)probateWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCPropertyOwnedAttribute class.
*/
@interface GCPropertyOwnedAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for propertyOwned
 
*/
+(GCPropertyOwnedAttribute *)propertyOwned;
/** Autogenerated convenience constructor for propertyOwned
 @param value .
*/
+(GCPropertyOwnedAttribute *)propertyOwnedWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for propertyOwned
 @param value .
*/
+(GCPropertyOwnedAttribute *)propertyOwnedWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCPublicationFactsAttribute class.
*/
@interface GCPublicationFactsAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for publicationFacts
 
*/
+(GCPublicationFactsAttribute *)publicationFacts;
/** Autogenerated convenience constructor for publicationFacts
 @param value .
*/
+(GCPublicationFactsAttribute *)publicationFactsWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for publicationFacts
 @param value .
*/
+(GCPublicationFactsAttribute *)publicationFactsWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCQualityOfDataAttribute class.
*/
@interface GCQualityOfDataAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for qualityOfData
 
*/
+(GCQualityOfDataAttribute *)qualityOfData;
/** Autogenerated convenience constructor for qualityOfData
 @param value .
*/
+(GCQualityOfDataAttribute *)qualityOfDataWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for qualityOfData
 @param value .
*/
+(GCQualityOfDataAttribute *)qualityOfDataWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCRecordFileNumberAttribute class.
*/
@interface GCRecordFileNumberAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for recordFileNumber
 
*/
+(GCRecordFileNumberAttribute *)recordFileNumber;
/** Autogenerated convenience constructor for recordFileNumber
 @param value .
*/
+(GCRecordFileNumberAttribute *)recordFileNumberWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for recordFileNumber
 @param value .
*/
+(GCRecordFileNumberAttribute *)recordFileNumberWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCRecordIdNumberAttribute class.
*/
@interface GCRecordIdNumberAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for recordIdNumber
 
*/
+(GCRecordIdNumberAttribute *)recordIdNumber;
/** Autogenerated convenience constructor for recordIdNumber
 @param value .
*/
+(GCRecordIdNumberAttribute *)recordIdNumberWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for recordIdNumber
 @param value .
*/
+(GCRecordIdNumberAttribute *)recordIdNumberWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCRelationshipDescriptorAttribute class.
*/
@interface GCRelationshipDescriptorAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for relationshipDescriptor
 
*/
+(GCRelationshipDescriptorAttribute *)relationshipDescriptor;
/** Autogenerated convenience constructor for relationshipDescriptor
 @param value .
*/
+(GCRelationshipDescriptorAttribute *)relationshipDescriptorWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for relationshipDescriptor
 @param value .
*/
+(GCRelationshipDescriptorAttribute *)relationshipDescriptorWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCReligionAttribute class.
*/
@interface GCReligionAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for religion
 
*/
+(GCReligionAttribute *)religion;
/** Autogenerated convenience constructor for religion
 @param value .
*/
+(GCReligionAttribute *)religionWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for religion
 @param value .
*/
+(GCReligionAttribute *)religionWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCRepositoryEntity class.
*/
@interface GCRepositoryEntity : GCEntity

// Methods:
/** Autogenerated convenience constructor for repository
 @param context .
*/
+(GCRepositoryEntity *)repositoryInContext:(GCContext *)context;

// Properties:
/// Autogenerated accessors for name. .
@property GCNameAttribute *name;
/// Autogenerated accessors for address. .
@property GCAddressAttribute *address;
/// Autogenerated accessors for phoneNumber. .
@property GCPhoneNumberAttribute *phoneNumber;
/// Autogenerated accessors for userReferenceNumbers.  // array of GCUserReferenceNumberAttribute.
@property NSMutableArray *userReferenceNumbers; // array of GCUserReferenceNumberAttribute

@end

/**
 Autogenerated GCRepositoryCitationRelationship class.
*/
@interface GCRepositoryCitationRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for repositoryCitation
 
*/
+(GCRepositoryCitationRelationship *)repositoryCitation;
/** Autogenerated convenience constructor for repositoryCitation
 @param target .
*/
+(GCRepositoryCitationRelationship *)repositoryCitationWithTarget:(GCEntity *)target;

// Properties:
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute
/// Autogenerated accessors for callNumbers.  // array of GCCallNumberAttribute.
@property NSMutableArray *callNumbers; // array of GCCallNumberAttribute

@end

/**
 Autogenerated GCResidenceAttribute class.
*/
@interface GCResidenceAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for residence
 
*/
+(GCResidenceAttribute *)residence;
/** Autogenerated convenience constructor for residence
 @param value .
*/
+(GCResidenceAttribute *)residenceWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for residence
 @param value .
*/
+(GCResidenceAttribute *)residenceWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCResponsibleAgencyAttribute class.
*/
@interface GCResponsibleAgencyAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for responsibleAgency
 
*/
+(GCResponsibleAgencyAttribute *)responsibleAgency;
/** Autogenerated convenience constructor for responsibleAgency
 @param value .
*/
+(GCResponsibleAgencyAttribute *)responsibleAgencyWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for responsibleAgency
 @param value .
*/
+(GCResponsibleAgencyAttribute *)responsibleAgencyWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCRestrictionNoticeAttribute class.
*/
@interface GCRestrictionNoticeAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for restrictionNotice
 
*/
+(GCRestrictionNoticeAttribute *)restrictionNotice;
/** Autogenerated convenience constructor for restrictionNotice
 @param value .
*/
+(GCRestrictionNoticeAttribute *)restrictionNoticeWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for restrictionNotice
 @param value .
*/
+(GCRestrictionNoticeAttribute *)restrictionNoticeWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCRetirementAttribute class.
*/
@interface GCRetirementAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for retirement
 
*/
+(GCRetirementAttribute *)retirement;
/** Autogenerated convenience constructor for retirement
 @param value .
*/
+(GCRetirementAttribute *)retirementWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for retirement
 @param value .
*/
+(GCRetirementAttribute *)retirementWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCRoleAttribute class.
*/
@interface GCRoleAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for role
 
*/
+(GCRoleAttribute *)role;
/** Autogenerated convenience constructor for role
 @param value .
*/
+(GCRoleAttribute *)roleWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for role
 @param value .
*/
+(GCRoleAttribute *)roleWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCSealingSpouseAttribute class.
*/
@interface GCSealingSpouseAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for sealingSpouse
 
*/
+(GCSealingSpouseAttribute *)sealingSpouse;
/** Autogenerated convenience constructor for sealingSpouse
 @param value .
*/
+(GCSealingSpouseAttribute *)sealingSpouseWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for sealingSpouse
 @param value .
*/
+(GCSealingSpouseAttribute *)sealingSpouseWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCSexAttribute class.
*/
@interface GCSexAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for sex
 
*/
+(GCSexAttribute *)sex;
/** Autogenerated convenience constructor for sex
 @param value .
*/
+(GCSexAttribute *)sexWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for sex
 @param value .
*/
+(GCSexAttribute *)sexWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCSocialSecurityNumberAttribute class.
*/
@interface GCSocialSecurityNumberAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for socialSecurityNumber
 
*/
+(GCSocialSecurityNumberAttribute *)socialSecurityNumber;
/** Autogenerated convenience constructor for socialSecurityNumber
 @param value .
*/
+(GCSocialSecurityNumberAttribute *)socialSecurityNumberWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for socialSecurityNumber
 @param value .
*/
+(GCSocialSecurityNumberAttribute *)socialSecurityNumberWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCSourceEntity class.
*/
@interface GCSourceEntity : GCEntity

// Methods:
/** Autogenerated convenience constructor for source
 @param context .
*/
+(GCSourceEntity *)sourceInContext:(GCContext *)context;

// Properties:
/// Autogenerated accessors for sourceData. .
@property GCSourceDataAttribute *sourceData;
/// Autogenerated accessors for author. .
@property GCAuthorAttribute *author;
/// Autogenerated accessors for title. .
@property GCTitleAttribute *title;
/// Autogenerated accessors for abbreviation. .
@property GCAbbreviationAttribute *abbreviation;
/// Autogenerated accessors for publicationFacts. .
@property GCPublicationFactsAttribute *publicationFacts;
/// Autogenerated accessors for text. .
@property GCTextAttribute *text;
/// Autogenerated accessors for repositoryCitation. .
@property GCRepositoryCitationRelationship *repositoryCitation;
/// Autogenerated accessors for multimedias. .
@property NSMutableArray *multimedias;
/// Autogenerated accessors for multimediaReferences.  // array of GCMultimediaReferenceRelationship.
@property NSMutableArray *multimediaReferences; // array of GCMultimediaReferenceRelationship
/// Autogenerated accessors for multimediaEmbeddeds.  // array of GCMultimediaEmbeddedAttribute.
@property NSMutableArray *multimediaEmbeddeds; // array of GCMultimediaEmbeddedAttribute
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute
/// Autogenerated accessors for userReferenceNumber. .
@property GCUserReferenceNumberAttribute *userReferenceNumber;
/// Autogenerated accessors for recordIdNumber. .
@property GCRecordIdNumberAttribute *recordIdNumber;

@end

/**
 Autogenerated GCSourceCitationRelationship class.
*/
@interface GCSourceCitationRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for sourceCitation
 
*/
+(GCSourceCitationRelationship *)sourceCitation;
/** Autogenerated convenience constructor for sourceCitation
 @param target .
*/
+(GCSourceCitationRelationship *)sourceCitationWithTarget:(GCEntity *)target;

// Properties:
/// Autogenerated accessors for page. .
@property GCPageAttribute *page;
/// Autogenerated accessors for data. .
@property GCDataAttribute *data;
/// Autogenerated accessors for qualityOfData. .
@property GCQualityOfDataAttribute *qualityOfData;
/// Autogenerated accessors for multimedias. .
@property NSMutableArray *multimedias;
/// Autogenerated accessors for multimediaReferences.  // array of GCMultimediaReferenceRelationship.
@property NSMutableArray *multimediaReferences; // array of GCMultimediaReferenceRelationship
/// Autogenerated accessors for multimediaEmbeddeds.  // array of GCMultimediaEmbeddedAttribute.
@property NSMutableArray *multimediaEmbeddeds; // array of GCMultimediaEmbeddedAttribute
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute

@end

/**
 Autogenerated GCSourceDataAttribute class.
*/
@interface GCSourceDataAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for sourceData
 
*/
+(GCSourceDataAttribute *)sourceData;
/** Autogenerated convenience constructor for sourceData
 @param value .
*/
+(GCSourceDataAttribute *)sourceDataWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for sourceData
 @param value .
*/
+(GCSourceDataAttribute *)sourceDataWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for eventsRecordeds.  // array of GCEventsRecordedAttribute.
@property NSMutableArray *eventsRecordeds; // array of GCEventsRecordedAttribute
/// Autogenerated accessors for responsibleAgency. .
@property GCResponsibleAgencyAttribute *responsibleAgency;
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute

@end

/**
 Autogenerated GCSourceEmbeddedAttribute class.
*/
@interface GCSourceEmbeddedAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for sourceEmbedded
 
*/
+(GCSourceEmbeddedAttribute *)sourceEmbedded;
/** Autogenerated convenience constructor for sourceEmbedded
 @param value .
*/
+(GCSourceEmbeddedAttribute *)sourceEmbeddedWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for sourceEmbedded
 @param value .
*/
+(GCSourceEmbeddedAttribute *)sourceEmbeddedWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for texts.  // array of GCTextAttribute.
@property NSMutableArray *texts; // array of GCTextAttribute
/// Autogenerated accessors for notes. .
@property NSMutableArray *notes;
/// Autogenerated accessors for noteReferences.  // array of GCNoteReferenceRelationship.
@property NSMutableArray *noteReferences; // array of GCNoteReferenceRelationship
/// Autogenerated accessors for noteEmbeddeds.  // array of GCNoteEmbeddedAttribute.
@property NSMutableArray *noteEmbeddeds; // array of GCNoteEmbeddedAttribute

@end

/**
 Autogenerated GCSpouseInFamilyRelationship class.
*/
@interface GCSpouseInFamilyRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for spouseInFamily
 
*/
+(GCSpouseInFamilyRelationship *)spouseInFamily;
/** Autogenerated convenience constructor for spouseInFamily
 @param target .
*/
+(GCSpouseInFamilyRelationship *)spouseInFamilyWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCStateAttribute class.
*/
@interface GCStateAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for state
 
*/
+(GCStateAttribute *)state;
/** Autogenerated convenience constructor for state
 @param value .
*/
+(GCStateAttribute *)stateWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for state
 @param value .
*/
+(GCStateAttribute *)stateWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCStatusAttribute class.
*/
@interface GCStatusAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for status
 
*/
+(GCStatusAttribute *)status;
/** Autogenerated convenience constructor for status
 @param value .
*/
+(GCStatusAttribute *)statusWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for status
 @param value .
*/
+(GCStatusAttribute *)statusWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCSubmissionEntity class.
*/
@interface GCSubmissionEntity : GCEntity

// Methods:
/** Autogenerated convenience constructor for submission
 @param context .
*/
+(GCSubmissionEntity *)submissionInContext:(GCContext *)context;

// Properties:
/// Autogenerated accessors for submitterReference. .
@property GCSubmitterReferenceRelationship *submitterReference;
/// Autogenerated accessors for familyFile. .
@property GCFamilyFileAttribute *familyFile;
/// Autogenerated accessors for temple. .
@property GCTempleAttribute *temple;
/// Autogenerated accessors for generationsOfAncestors. .
@property GCGenerationsOfAncestorsAttribute *generationsOfAncestors;
/// Autogenerated accessors for generationsOfDescendants. .
@property GCGenerationsOfDescendantsAttribute *generationsOfDescendants;
/// Autogenerated accessors for ordinance. .
@property GCOrdinanceAttribute *ordinance;
/// Autogenerated accessors for recordIdNumber. .
@property GCRecordIdNumberAttribute *recordIdNumber;
/// Autogenerated accessors for userReferenceNumbers.  // array of GCUserReferenceNumberAttribute.
@property NSMutableArray *userReferenceNumbers; // array of GCUserReferenceNumberAttribute

@end

/**
 Autogenerated GCSubmissionReferenceRelationship class.
*/
@interface GCSubmissionReferenceRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for submissionReference
 
*/
+(GCSubmissionReferenceRelationship *)submissionReference;
/** Autogenerated convenience constructor for submissionReference
 @param target .
*/
+(GCSubmissionReferenceRelationship *)submissionReferenceWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCSubmitterEntity class.
*/
@interface GCSubmitterEntity : GCEntity

// Methods:
/** Autogenerated convenience constructor for submitter
 @param context .
*/
+(GCSubmitterEntity *)submitterInContext:(GCContext *)context;

// Properties:
/// Autogenerated accessors for name.  //  NB: required property.
@property GCNameAttribute *name; //  NB: required property
/// Autogenerated accessors for address. .
@property GCAddressAttribute *address;
/// Autogenerated accessors for phoneNumber. .
@property GCPhoneNumberAttribute *phoneNumber;
/// Autogenerated accessors for multimedias. .
@property NSMutableArray *multimedias;
/// Autogenerated accessors for multimediaReferences.  // array of GCMultimediaReferenceRelationship.
@property NSMutableArray *multimediaReferences; // array of GCMultimediaReferenceRelationship
/// Autogenerated accessors for multimediaEmbeddeds.  // array of GCMultimediaEmbeddedAttribute.
@property NSMutableArray *multimediaEmbeddeds; // array of GCMultimediaEmbeddedAttribute
/// Autogenerated accessors for language. .
@property GCLanguageAttribute *language;
/// Autogenerated accessors for recordFileNumber. .
@property GCRecordFileNumberAttribute *recordFileNumber;
/// Autogenerated accessors for ancestralFileNumber. .
@property GCAncestralFileNumberAttribute *ancestralFileNumber;
/// Autogenerated accessors for userReferenceNumbers.  // array of GCUserReferenceNumberAttribute.
@property NSMutableArray *userReferenceNumbers; // array of GCUserReferenceNumberAttribute

@end

/**
 Autogenerated GCSubmitterReferenceRelationship class.
*/
@interface GCSubmitterReferenceRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for submitterReference
 
*/
+(GCSubmitterReferenceRelationship *)submitterReference;
/** Autogenerated convenience constructor for submitterReference
 @param target .
*/
+(GCSubmitterReferenceRelationship *)submitterReferenceWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCSurnameAttribute class.
*/
@interface GCSurnameAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for surname
 
*/
+(GCSurnameAttribute *)surname;
/** Autogenerated convenience constructor for surname
 @param value .
*/
+(GCSurnameAttribute *)surnameWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for surname
 @param value .
*/
+(GCSurnameAttribute *)surnameWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCSurnamePrefixAttribute class.
*/
@interface GCSurnamePrefixAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for surnamePrefix
 
*/
+(GCSurnamePrefixAttribute *)surnamePrefix;
/** Autogenerated convenience constructor for surnamePrefix
 @param value .
*/
+(GCSurnamePrefixAttribute *)surnamePrefixWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for surnamePrefix
 @param value .
*/
+(GCSurnamePrefixAttribute *)surnamePrefixWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCTempleAttribute class.
*/
@interface GCTempleAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for temple
 
*/
+(GCTempleAttribute *)temple;
/** Autogenerated convenience constructor for temple
 @param value .
*/
+(GCTempleAttribute *)templeWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for temple
 @param value .
*/
+(GCTempleAttribute *)templeWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCTextAttribute class.
*/
@interface GCTextAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for text
 
*/
+(GCTextAttribute *)text;
/** Autogenerated convenience constructor for text
 @param value .
*/
+(GCTextAttribute *)textWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for text
 @param value .
*/
+(GCTextAttribute *)textWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCTimeAttribute class.
*/
@interface GCTimeAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for time
 
*/
+(GCTimeAttribute *)time;
/** Autogenerated convenience constructor for time
 @param value .
*/
+(GCTimeAttribute *)timeWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for time
 @param value .
*/
+(GCTimeAttribute *)timeWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCTitleAttribute class.
*/
@interface GCTitleAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for title
 
*/
+(GCTitleAttribute *)title;
/** Autogenerated convenience constructor for title
 @param value .
*/
+(GCTitleAttribute *)titleWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for title
 @param value .
*/
+(GCTitleAttribute *)titleWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCTypeDescriptionAttribute class.
*/
@interface GCTypeDescriptionAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for typeDescription
 
*/
+(GCTypeDescriptionAttribute *)typeDescription;
/** Autogenerated convenience constructor for typeDescription
 @param value .
*/
+(GCTypeDescriptionAttribute *)typeDescriptionWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for typeDescription
 @param value .
*/
+(GCTypeDescriptionAttribute *)typeDescriptionWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCUserReferenceNumberAttribute class.
*/
@interface GCUserReferenceNumberAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for userReferenceNumber
 
*/
+(GCUserReferenceNumberAttribute *)userReferenceNumber;
/** Autogenerated convenience constructor for userReferenceNumber
 @param value .
*/
+(GCUserReferenceNumberAttribute *)userReferenceNumberWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for userReferenceNumber
 @param value .
*/
+(GCUserReferenceNumberAttribute *)userReferenceNumberWithValue:(GCValue *)value;

// Properties:
/// Autogenerated accessors for typeDescription. .
@property GCTypeDescriptionAttribute *typeDescription;

@end

/**
 Autogenerated GCVersionAttribute class.
*/
@interface GCVersionAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for version
 
*/
+(GCVersionAttribute *)version;
/** Autogenerated convenience constructor for version
 @param value .
*/
+(GCVersionAttribute *)versionWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for version
 @param value .
*/
+(GCVersionAttribute *)versionWithValue:(GCValue *)value;

// Properties:


@end

/**
 Autogenerated GCWifeRelationship class.
*/
@interface GCWifeRelationship : GCRelationship

// Methods:
/** Autogenerated convenience constructor for wife
 
*/
+(GCWifeRelationship *)wife;
/** Autogenerated convenience constructor for wife
 @param target .
*/
+(GCWifeRelationship *)wifeWithTarget:(GCEntity *)target;

// Properties:


@end

/**
 Autogenerated GCWillAttribute class.
*/
@interface GCWillAttribute : GCAttribute

// Methods:
/** Autogenerated convenience constructor for will
 
*/
+(GCWillAttribute *)will;
/** Autogenerated convenience constructor for will
 @param value .
*/
+(GCWillAttribute *)willWithGedcomStringValue:(NSString *)value;
/** Autogenerated convenience constructor for will
 @param value .
*/
+(GCWillAttribute *)willWithValue:(GCValue *)value;

// Properties:


@end

