/*
 This file was autogenerated by tags.py 
 */

#import "GCAdoptedByWhichParentAttribute.h"

#import "GCObject_internal.h"



@implementation GCAdoptedByWhichParentAttribute {

}

+ (GCTag *)gedTag
{
	return [GCTag tagWithClassName:@"GCAdoptedByWhichParentAttribute"];
}

// Methods:
/** Initializes and returns a adoptedByWhichParent.

 
 @return A new adoptedByWhichParent.
*/
+(GCAdoptedByWhichParentAttribute *)adoptedByWhichParent
{
	return [[self alloc] init];
}
/** Initializes and returns a adoptedByWhichParent.

 @param value The value as a GCValue object.
 @return A new adoptedByWhichParent.
*/
+(GCAdoptedByWhichParentAttribute *)adoptedByWhichParentWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a adoptedByWhichParent.

 @param value The value as an NSString.
 @return A new adoptedByWhichParent.
*/
+(GCAdoptedByWhichParentAttribute *)adoptedByWhichParentWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"adoptedByWhichParent"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

