/*
 This file was autogenerated by tags.py 
 */

#import "GCAddressLine2Attribute.h"



@implementation GCAddressLine2Attribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a addressLine2.

 
 @return A new addressLine2.
*/
+(instancetype)addressLine2
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a addressLine2.

 @param value The value as a GCValue object.
 @return A new addressLine2.
*/
+(instancetype)addressLine2WithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a addressLine2.

 @param value The value as an NSString.
 @return A new addressLine2.
*/
+(instancetype)addressLine2WithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
