/*
 This file was autogenerated by tags.py 
 */

#import "GCAgeAttribute.h"

#import "GCObject_internal.h"
#import "GCEntity_internal.h"



@implementation GCAgeAttribute {

}

// Methods:
/** Initializes and returns a age.

 
 @return A new age.
*/
+(GCAgeAttribute *)age
{
	return [[self alloc] init];
}
/** Initializes and returns a age.

 @param value The value as a GCValue object.
 @return A new age.
*/
+(GCAgeAttribute *)ageWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a age.

 @param value The value as an NSString.
 @return A new age.
*/
+(GCAgeAttribute *)ageWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"age"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

