/*
 This file was autogenerated by tags.py 
 */

#import "GCAncestralFileNumberAttribute.h"

#import "GCObject_internal.h"



@implementation GCAncestralFileNumberAttribute {

}

+ (GCTag *)gedTag
{
	return [GCTag tagWithClassName:@"GCAncestralFileNumberAttribute"];
}

// Methods:
/** Initializes and returns a ancestralFileNumber.

 
 @return A new ancestralFileNumber.
*/
+(GCAncestralFileNumberAttribute *)ancestralFileNumber
{
	return [[self alloc] init];
}
/** Initializes and returns a ancestralFileNumber.

 @param value The value as a GCValue object.
 @return A new ancestralFileNumber.
*/
+(GCAncestralFileNumberAttribute *)ancestralFileNumberWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a ancestralFileNumber.

 @param value The value as an NSString.
 @return A new ancestralFileNumber.
*/
+(GCAncestralFileNumberAttribute *)ancestralFileNumberWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"ancestralFileNumber"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

