/*
 This file was autogenerated by tags.py 
 */

#import "GCAncestorInterestRelationship.h"

#import "GCObject_internal.h"
#import "GCProperty_internal.h"



@implementation GCAncestorInterestRelationship {

}

// Methods:
/** Initializes and returns a ancestorInterest.

 
 @return A new ancestorInterest.
*/
+(GCAncestorInterestRelationship *)ancestorInterest
{
	return [[self alloc] init];
}
- (id)init
{
	self = [super _initWithType:@"ancestorInterest"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

