/*
 This file was autogenerated by tags.py 
 */

#import "GCAuthorAttribute.h"



@implementation GCAuthorAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a author.

 
 @return A new author.
*/
+(instancetype)author
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a author.

 @param value The value as a GCValue object.
 @return A new author.
*/
+(instancetype)authorWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a author.

 @param value The value as an NSString.
 @return A new author.
*/
+(instancetype)authorWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

