/*
 This file was autogenerated by tags.py 
 */

#import "GCCallNumberAttribute.h"

#import "GCObject_internal.h"
#import "GCContext_internal.h"

#import "GCMediaTypeAttribute.h"

@implementation GCCallNumberAttribute {
	GCMediaTypeAttribute *_mediaType;
}

// Methods:
/** Initializes and returns a callNumber.

 
 @return A new callNumber.
*/
+(GCCallNumberAttribute *)callNumber
{
	return [[self alloc] init];
}
/** Initializes and returns a callNumber.

 @param value The value as a GCValue object.
 @return A new callNumber.
*/
+(GCCallNumberAttribute *)callNumberWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a callNumber.

 @param value The value as an NSString.
 @return A new callNumber.
*/
+(GCCallNumberAttribute *)callNumberWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"callNumber"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:

- (void)setMediaType:(id)obj
{
	[(GCCallNumberAttribute *)[self.context.undoManager prepareWithInvocationTarget:self] setMediaType:_mediaType];
	[self.context.undoManager setActionName:@"Undo mediaType"]; //TODO
	
	if (_mediaType) {
		[obj setValue:nil forKey:@"describedObject"];
	}
	
	if ([obj valueForKey:@"describedObject"]) {
		[((GCObject *)[obj valueForKey:@"describedObject"]).mutableProperties removeObject:obj];
	}
	
	[obj setValue:self forKey:@"describedObject"];
	
	_mediaType = (id)obj;
}

- (GCMediaTypeAttribute *)mediaType
{
	return _mediaType;
}


@end

