/*
 This file was autogenerated by tags.py 
 */

#import "GCCharacterSetAttribute.h"

#import "GCObject_internal.h"

#import "GCVersionAttribute.h"

@implementation GCCharacterSetAttribute {
	GCVersionAttribute *_version;
}

// Methods:
/// @name Initializing

/** Initializes and returns a characterSet.

 
 @return A new characterSet.
*/
+(instancetype)characterSet
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a characterSet.

 @param value The value as a GCValue object.
 @return A new characterSet.
*/
+(instancetype)characterSetWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a characterSet.

 @param value The value as an NSString.
 @return A new characterSet.
*/
+(instancetype)characterSetWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:
@dynamic version;

@end

