/*
 This file was autogenerated by tags.py 
 */

#import "GCCharacterSetAttribute.h"

#import "GCObject_internal.h"

#import "GCVersionAttribute.h"

@implementation GCCharacterSetAttribute {
	GCVersionAttribute *_version;
}

// Methods:
/** Initializes and returns a characterSet.

 
 @return A new characterSet.
*/
+(GCCharacterSetAttribute *)characterSet
{
	return [[self alloc] init];
}
/** Initializes and returns a characterSet.

 @param value The value as a GCValue object.
 @return A new characterSet.
*/
+(GCCharacterSetAttribute *)characterSetWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a characterSet.

 @param value The value as an NSString.
 @return A new characterSet.
*/
+(GCCharacterSetAttribute *)characterSetWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"characterSet"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:

- (void)setVersion:(id)obj
{
	NSBundle *frameworkBundle = [NSBundle bundleForClass:[self class]];
	
	NSString *formatString = [frameworkBundle localizedStringForKey:@"Undo %@"
															  value:@"Undo %@"
															  table:@"Misc"];
	
	[(GCCharacterSetAttribute *)[self.undoManager prepareWithInvocationTarget:self] setVersion:_version];
	[self.undoManager setActionName:[NSString stringWithFormat:formatString, self.localizedType]];
	
	if (_version) {
		[obj setValue:nil forKey:@"describedObject"];
	}
	
	if ([obj valueForKey:@"describedObject"]) {
		[((GCObject *)[obj valueForKey:@"describedObject"]).mutableProperties removeObject:obj];
	}
	
	[obj setValue:self forKey:@"describedObject"];
	
	_version = (id)obj;
}

- (GCVersionAttribute *)version
{
	return _version;
}


@end

