/*
 This file was autogenerated by tags.py 
 */

#import "GCDestinationAttribute.h"

#import "GCObject_internal.h"



@implementation GCDestinationAttribute {

}

// Methods:
/** Initializes and returns a destination.

 
 @return A new destination.
*/
+(instancetype)destination
{
	return [[self alloc] init];
}
/** Initializes and returns a destination.

 @param value The value as a GCValue object.
 @return A new destination.
*/
+(instancetype)destinationWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a destination.

 @param value The value as an NSString.
 @return A new destination.
*/
+(instancetype)destinationWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

