/*
 This file was autogenerated by tags.py 
 */

#import "GCDescendantInterestRelationship.h"

#import "GCObject_internal.h"



@implementation GCDescendantInterestRelationship {

}

// Methods:
/** Initializes and returns a descendantInterest.

 
 @return A new descendantInterest.
*/
+(instancetype)descendantInterest
{
	return [[self alloc] init];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

