/*
 This file was autogenerated by tags.py 
 */

#import "GCDivorceAttribute.h"

@implementation GCDivorceAttribute {
	GCHusbandDetailAttribute *_husbandDetail;
	GCWifeDetailAttribute *_wifeDetail;
}

// Methods:
/// @name Initializing

/** Initializes and returns a divorce.

 
 @return A new divorce.
*/
+(instancetype)divorce
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a divorce.

 @param value The value as a GCValue object.
 @return A new divorce.
*/
+(instancetype)divorceWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a divorce.

 @param value The value as an NSString.
 @return A new divorce.
*/
+(instancetype)divorceWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:
@dynamic husbandDetail;
@dynamic wifeDetail;

@end
