/*
 This file was autogenerated by tags.py 
 */

#import "GCEngagementAttribute.h"

#import "GCTagAccessAdditions.h"
#import "GCObject_internal.h"
#import "Gedcom_internal.h"

@implementation GCEngagementAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a engagement.

 
 @return A new engagement.
*/
+(instancetype)engagement
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a engagement.

 @param value The value as a GCValue object.
 @return A new engagement.
*/
+(instancetype)engagementWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a engagement.

 @param value The value as an NSString.
 @return A new engagement.
*/
+(instancetype)engagementWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
