/*
 This file was autogenerated by tags.py 
 */

#import "GCEventCitedAttribute.h"

#import "GCRoleAttribute.h"

@implementation GCEventCitedAttribute {
	GCRoleAttribute *_role;
}

// Methods:
/// @name Initializing

/** Initializes and returns a eventCited.

 
 @return A new eventCited.
*/
+(instancetype)eventCited
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a eventCited.

 @param value The value as a GCValue object.
 @return A new eventCited.
*/
+(instancetype)eventCitedWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a eventCited.

 @param value The value as an NSString.
 @return A new eventCited.
*/
+(instancetype)eventCitedWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:
@dynamic role;

@end
