/*
 This file was autogenerated by tags.py 
 */

#import "GCGedcomAttribute.h"

#import "GCObject_internal.h"

#import "GCGedcomFormatAttribute.h"
#import "GCVersionAttribute.h"

@implementation GCGedcomAttribute {
	GCVersionAttribute *_version;
	GCGedcomFormatAttribute *_gedcomFormat;
}

+ (GCTag *)gedTag
{
	return [GCTag tagWithClassName:@"GCGedcomAttribute"];
}

// Methods:
/** Initializes and returns a gedcom.

 
 @return A new gedcom.
*/
+(GCGedcomAttribute *)gedcom
{
	return [[self alloc] init];
}
/** Initializes and returns a gedcom.

 @param value The value as a GCValue object.
 @return A new gedcom.
*/
+(GCGedcomAttribute *)gedcomWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a gedcom.

 @param value The value as an NSString.
 @return A new gedcom.
*/
+(GCGedcomAttribute *)gedcomWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"gedcom"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:
@dynamic version;
@dynamic gedcomFormat;

@end

