/*
 This file was autogenerated by tags.py 
 */

#import "GCGedcomAttribute.h"

#import "GCObject_internal.h"
#import "GCProperty_internal.h"

#import "GCGedcomFormatAttribute.h"
#import "GCVersionAttribute.h"

@implementation GCGedcomAttribute {
	GCVersionAttribute *_version;
	GCGedcomFormatAttribute *_gedcomFormat;
}

// Methods:
/** Initializes and returns a gedcom.

 
 @return A new gedcom.
*/
+(GCGedcomAttribute *)gedcom
{
	return [[self alloc] init];
}
/** Initializes and returns a gedcom.

 @param value The value as a GCValue object.
 @return A new gedcom.
*/
+(GCGedcomAttribute *)gedcomWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a gedcom.

 @param value The value as an NSString.
 @return A new gedcom.
*/
+(GCGedcomAttribute *)gedcomWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"gedcom"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:

- (void)setVersion:(GCProperty *)obj
{
	if (_version) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_version = (id)obj;
}

- (GCVersionAttribute *)version
{
	return _version;
}


- (void)setGedcomFormat:(GCProperty *)obj
{
	if (_gedcomFormat) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_gedcomFormat = (id)obj;
}

- (GCGedcomFormatAttribute *)gedcomFormat
{
	return _gedcomFormat;
}


@end

