/*
 This file was autogenerated by tags.py 
 */

#import "GCHeaderSourceDataAttribute.h"

#import "GCObject_internal.h"

#import "GCCopyrightAttribute.h"
#import "GCDateAttribute.h"

@implementation GCHeaderSourceDataAttribute {
	GCDateAttribute *_date;
	GCCopyrightAttribute *_copyright;
}

+ (GCTag *)gedTag
{
	return [GCTag tagWithClassName:@"GCHeaderSourceDataAttribute"];
}

// Methods:
/** Initializes and returns a headerSourceData.

 
 @return A new headerSourceData.
*/
+(GCHeaderSourceDataAttribute *)headerSourceData
{
	return [[self alloc] init];
}
/** Initializes and returns a headerSourceData.

 @param value The value as a GCValue object.
 @return A new headerSourceData.
*/
+(GCHeaderSourceDataAttribute *)headerSourceDataWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a headerSourceData.

 @param value The value as an NSString.
 @return A new headerSourceData.
*/
+(GCHeaderSourceDataAttribute *)headerSourceDataWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"headerSourceData"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:
@dynamic date;
@dynamic copyright;

@end

