/*
 This file was autogenerated by tags.py 
 */

#import "GCIndividualEntity.h"

#import "GCObject_internal.h"

#import "GCAdoptionAttribute.h"
#import "GCAdultChristeningAttribute.h"
#import "GCAliasRelationship.h"
#import "GCAncestorInterestRelationship.h"
#import "GCAncestralFileNumberAttribute.h"
#import "GCAssociationRelationship.h"
#import "GCBaptismAttribute.h"
#import "GCBarMitzvahAttribute.h"
#import "GCBasMitzvahAttribute.h"
#import "GCBirthAttribute.h"
#import "GCBlessingAttribute.h"
#import "GCBurialAttribute.h"
#import "GCCasteAttribute.h"
#import "GCCensusAttribute.h"
#import "GCChangeInfoAttribute.h"
#import "GCChildInFamilyRelationship.h"
#import "GCChristeningAttribute.h"
#import "GCConfirmationAttribute.h"
#import "GCCremationAttribute.h"
#import "GCDeathAttribute.h"
#import "GCDescendantInterestRelationship.h"
#import "GCEducationAttribute.h"
#import "GCEmigrationAttribute.h"
#import "GCFirstCommunionAttribute.h"
#import "GCGenerationsOfDescendantsAttribute.h"
#import "GCGenericEventAttribute.h"
#import "GCGraduationAttribute.h"
#import "GCIdentNumberAttribute.h"
#import "GCImmigrationAttribute.h"
#import "GCLDSBaptismAttribute.h"
#import "GCLDSConfirmationAttribute.h"
#import "GCLDSEndowmentAttribute.h"
#import "GCLDSSealingChildAttribute.h"
#import "GCMultimediaEmbeddedAttribute.h"
#import "GCMultimediaReferenceRelationship.h"
#import "GCNationalityAttribute.h"
#import "GCNaturalizationAttribute.h"
#import "GCNoteEmbeddedAttribute.h"
#import "GCNoteReferenceRelationship.h"
#import "GCNumberOfChildrenAttribute.h"
#import "GCNumberOfMarriagesAttribute.h"
#import "GCOccupationAttribute.h"
#import "GCOrdinationAttribute.h"
#import "GCPersonalNameAttribute.h"
#import "GCPhysicalDescriptionAttribute.h"
#import "GCProbateAttribute.h"
#import "GCPropertyOwnedAttribute.h"
#import "GCRecordFileNumberAttribute.h"
#import "GCRecordIdNumberAttribute.h"
#import "GCReligionAttribute.h"
#import "GCResidenceAttribute.h"
#import "GCRestrictionNoticeAttribute.h"
#import "GCRetirementAttribute.h"
#import "GCSexAttribute.h"
#import "GCSocialSecurityNumberAttribute.h"
#import "GCSourceCitationRelationship.h"
#import "GCSourceEmbeddedAttribute.h"
#import "GCSpouseInFamilyRelationship.h"
#import "GCSubmitterReferenceRelationship.h"
#import "GCTitleAttribute.h"
#import "GCUserReferenceNumberAttribute.h"
#import "GCWillAttribute.h"

@implementation GCIndividualEntity {
	GCRestrictionNoticeAttribute *_restrictionNotice;
	NSMutableArray *_personalNames;
	GCSexAttribute *_sex;
	NSMutableArray *_births;
	NSMutableArray *_christenings;
	NSMutableArray *_deaths;
	NSMutableArray *_burials;
	NSMutableArray *_cremations;
	NSMutableArray *_adoptions;
	NSMutableArray *_baptisms;
	NSMutableArray *_barMitzvahs;
	NSMutableArray *_basMitzvahs;
	NSMutableArray *_blessings;
	NSMutableArray *_adultChristenings;
	NSMutableArray *_confirmations;
	NSMutableArray *_firstCommunions;
	NSMutableArray *_ordinations;
	NSMutableArray *_naturalizations;
	NSMutableArray *_emigrations;
	NSMutableArray *_immigrations;
	NSMutableArray *_censuses;
	NSMutableArray *_probates;
	NSMutableArray *_wills;
	NSMutableArray *_graduations;
	NSMutableArray *_retirements;
	NSMutableArray *_genericEvents;
	NSMutableArray *_castes;
	NSMutableArray *_physicalDescriptions;
	NSMutableArray *_generationsOfDescendantss;
	NSMutableArray *_educations;
	NSMutableArray *_identNumbers;
	NSMutableArray *_nationalities;
	NSMutableArray *_numberOfChildrens;
	NSMutableArray *_numberOfMarriagess;
	NSMutableArray *_occupations;
	NSMutableArray *_propertyOwneds;
	NSMutableArray *_religions;
	NSMutableArray *_residences;
	NSMutableArray *_socialSecurityNumbers;
	NSMutableArray *_titles;
	NSMutableArray *_lDSBaptisms;
	NSMutableArray *_lDSConfirmations;
	NSMutableArray *_lDSEndowments;
	NSMutableArray *_lDSSealingChilds;
	NSMutableArray *_childInFamilies;
	NSMutableArray *_spouseInFamilies;
	NSMutableArray *_submitterReferences;
	NSMutableArray *_associations;
	NSMutableArray *_aliases;
	NSMutableArray *_ancestorInterests;
	NSMutableArray *_descendantInterests;
	NSMutableArray *_sourceCitations;
	NSMutableArray *_sourceEmbeddeds;
	NSMutableArray *_multimediaReferences;
	NSMutableArray *_multimediaEmbeddeds;
	NSMutableArray *_noteReferences;
	NSMutableArray *_noteEmbeddeds;
	NSMutableArray *_recordFileNumbers;
	NSMutableArray *_ancestralFileNumbers;
	NSMutableArray *_userReferenceNumbers;
	GCRecordIdNumberAttribute *_recordIdNumber;
	GCChangeInfoAttribute *_changeInfo;
}

+ (GCTag *)gedTag
{
	return [GCTag tagWithClassName:@"GCIndividualEntity"];
}

// Methods:
/** Initializes and returns a individual.

 @param context The context in which to create the entity.
 @return A new individual.
*/
+(GCIndividualEntity *)individualInContext:(GCContext *)context
{
	return [[self alloc] initInContext:context];
}
- (id)initInContext:(GCContext *)context
{
	self = [super _initWithType:@"individual" inContext:context];
	
	if (self) {
		// initialize ivars, if any:
		_personalNames = [NSMutableArray array];
		_births = [NSMutableArray array];
		_christenings = [NSMutableArray array];
		_deaths = [NSMutableArray array];
		_burials = [NSMutableArray array];
		_cremations = [NSMutableArray array];
		_adoptions = [NSMutableArray array];
		_baptisms = [NSMutableArray array];
		_barMitzvahs = [NSMutableArray array];
		_basMitzvahs = [NSMutableArray array];
		_blessings = [NSMutableArray array];
		_adultChristenings = [NSMutableArray array];
		_confirmations = [NSMutableArray array];
		_firstCommunions = [NSMutableArray array];
		_ordinations = [NSMutableArray array];
		_naturalizations = [NSMutableArray array];
		_emigrations = [NSMutableArray array];
		_immigrations = [NSMutableArray array];
		_censuses = [NSMutableArray array];
		_probates = [NSMutableArray array];
		_wills = [NSMutableArray array];
		_graduations = [NSMutableArray array];
		_retirements = [NSMutableArray array];
		_genericEvents = [NSMutableArray array];
		_castes = [NSMutableArray array];
		_physicalDescriptions = [NSMutableArray array];
		_generationsOfDescendantss = [NSMutableArray array];
		_educations = [NSMutableArray array];
		_identNumbers = [NSMutableArray array];
		_nationalities = [NSMutableArray array];
		_numberOfChildrens = [NSMutableArray array];
		_numberOfMarriagess = [NSMutableArray array];
		_occupations = [NSMutableArray array];
		_propertyOwneds = [NSMutableArray array];
		_religions = [NSMutableArray array];
		_residences = [NSMutableArray array];
		_socialSecurityNumbers = [NSMutableArray array];
		_titles = [NSMutableArray array];
		_lDSBaptisms = [NSMutableArray array];
		_lDSConfirmations = [NSMutableArray array];
		_lDSEndowments = [NSMutableArray array];
		_lDSSealingChilds = [NSMutableArray array];
		_childInFamilies = [NSMutableArray array];
		_spouseInFamilies = [NSMutableArray array];
		_submitterReferences = [NSMutableArray array];
		_associations = [NSMutableArray array];
		_aliases = [NSMutableArray array];
		_ancestorInterests = [NSMutableArray array];
		_descendantInterests = [NSMutableArray array];
		_sourceCitations = [NSMutableArray array];
		_sourceEmbeddeds = [NSMutableArray array];
		_multimediaReferences = [NSMutableArray array];
		_multimediaEmbeddeds = [NSMutableArray array];
		_noteReferences = [NSMutableArray array];
		_noteEmbeddeds = [NSMutableArray array];
		_recordFileNumbers = [NSMutableArray array];
		_ancestralFileNumbers = [NSMutableArray array];
		_userReferenceNumbers = [NSMutableArray array];
	}
	
	return self;
}


// Properties:
@dynamic restrictionNotice;
@dynamic personalNames;
@dynamic mutablePersonalNames;
@dynamic sex;
@dynamic individualEvents;
@dynamic births;
@dynamic mutableBirths;
@dynamic christenings;
@dynamic mutableChristenings;
@dynamic deaths;
@dynamic mutableDeaths;
@dynamic burials;
@dynamic mutableBurials;
@dynamic cremations;
@dynamic mutableCremations;
@dynamic adoptions;
@dynamic mutableAdoptions;
@dynamic baptisms;
@dynamic mutableBaptisms;
@dynamic barMitzvahs;
@dynamic mutableBarMitzvahs;
@dynamic basMitzvahs;
@dynamic mutableBasMitzvahs;
@dynamic blessings;
@dynamic mutableBlessings;
@dynamic adultChristenings;
@dynamic mutableAdultChristenings;
@dynamic confirmations;
@dynamic mutableConfirmations;
@dynamic firstCommunions;
@dynamic mutableFirstCommunions;
@dynamic ordinations;
@dynamic mutableOrdinations;
@dynamic naturalizations;
@dynamic mutableNaturalizations;
@dynamic emigrations;
@dynamic mutableEmigrations;
@dynamic immigrations;
@dynamic mutableImmigrations;
@dynamic censuses;
@dynamic mutableCensuses;
@dynamic probates;
@dynamic mutableProbates;
@dynamic wills;
@dynamic mutableWills;
@dynamic graduations;
@dynamic mutableGraduations;
@dynamic retirements;
@dynamic mutableRetirements;
@dynamic genericEvents;
@dynamic mutableGenericEvents;
@dynamic individualAttributes;
@dynamic castes;
@dynamic mutableCastes;
@dynamic physicalDescriptions;
@dynamic mutablePhysicalDescriptions;
@dynamic generationsOfDescendantss;
@dynamic mutableGenerationsOfDescendantss;
@dynamic educations;
@dynamic mutableEducations;
@dynamic identNumbers;
@dynamic mutableIdentNumbers;
@dynamic nationalities;
@dynamic mutableNationalities;
@dynamic numberOfChildrens;
@dynamic mutableNumberOfChildrens;
@dynamic numberOfMarriagess;
@dynamic mutableNumberOfMarriagess;
@dynamic occupations;
@dynamic mutableOccupations;
@dynamic propertyOwneds;
@dynamic mutablePropertyOwneds;
@dynamic religions;
@dynamic mutableReligions;
@dynamic residences;
@dynamic mutableResidences;
@dynamic socialSecurityNumbers;
@dynamic mutableSocialSecurityNumbers;
@dynamic titles;
@dynamic mutableTitles;
@dynamic individualLDSOrdinances;
@dynamic lDSBaptisms;
@dynamic mutableLDSBaptisms;
@dynamic lDSConfirmations;
@dynamic mutableLDSConfirmations;
@dynamic lDSEndowments;
@dynamic mutableLDSEndowments;
@dynamic lDSSealingChilds;
@dynamic mutableLDSSealingChilds;
@dynamic childInFamilies;
@dynamic mutableChildInFamilies;
@dynamic spouseInFamilies;
@dynamic mutableSpouseInFamilies;
@dynamic submitterReferences;
@dynamic mutableSubmitterReferences;
@dynamic associations;
@dynamic mutableAssociations;
@dynamic aliases;
@dynamic mutableAliases;
@dynamic ancestorInterests;
@dynamic mutableAncestorInterests;
@dynamic descendantInterests;
@dynamic mutableDescendantInterests;
@dynamic sources;
@dynamic sourceCitations;
@dynamic mutableSourceCitations;
@dynamic sourceEmbeddeds;
@dynamic mutableSourceEmbeddeds;
@dynamic multimedias;
@dynamic multimediaReferences;
@dynamic mutableMultimediaReferences;
@dynamic multimediaEmbeddeds;
@dynamic mutableMultimediaEmbeddeds;
@dynamic notes;
@dynamic noteReferences;
@dynamic mutableNoteReferences;
@dynamic noteEmbeddeds;
@dynamic mutableNoteEmbeddeds;
@dynamic recordFileNumbers;
@dynamic mutableRecordFileNumbers;
@dynamic ancestralFileNumbers;
@dynamic mutableAncestralFileNumbers;
@dynamic userReferenceNumbers;
@dynamic mutableUserReferenceNumbers;
@dynamic recordIdNumber;
@dynamic changeInfo;

@end

