/*
 This file was autogenerated by tags.py 
 */

#import "GCLDSConfirmationAttribute.h"

#import "GCTagAccessAdditions.h"
#import "GCObject_internal.h"
#import "Gedcom_internal.h"

@implementation GCLDSConfirmationAttribute {
	GCLDSBaptismStatusAttribute *_lDSBaptismStatus;
}

// Methods:
/// @name Initializing

/** Initializes and returns a lDSConfirmation.

 
 @return A new lDSConfirmation.
*/
+(instancetype)lDSConfirmation
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a lDSConfirmation.

 @param value The value as a GCValue object.
 @return A new lDSConfirmation.
*/
+(instancetype)lDSConfirmationWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a lDSConfirmation.

 @param value The value as an NSString.
 @return A new lDSConfirmation.
*/
+(instancetype)lDSConfirmationWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:

- (id)lDSBaptismStatus
{
	return _lDSBaptismStatus;
}
	
- (void)setLDSBaptismStatus:(id)obj
{
	if (!_isBuildingFromGedcom) {
		NSUndoManager *uM = [self valueForKey:@"undoManager"];
		@synchronized (uM) {
			[uM beginUndoGrouping];
			[(GCLDSConfirmationAttribute *)[uM prepareWithInvocationTarget:self] setLDSBaptismStatus:_lDSBaptismStatus];
			[uM setActionName:[NSString stringWithFormat:GCLocalizedString(@"Undo %@", @"Misc"), self.localizedType]];
			[uM endUndoGrouping];
		}
	}
	
	if (_lDSBaptismStatus) {
		[(id)_lDSBaptismStatus setValue:nil forKey:@"describedObject"];
	}
	
	[[obj valueForKeyPath:@"describedObject.mutableProperties"] removeObject:obj];
	
	[obj setValue:self forKey:@"describedObject"];
	
	_lDSBaptismStatus = obj;
}


@end
