/*
 This file was autogenerated by tags.py 
 */

#import "GCLDSSealingSpouseStatusAttribute.h"

#import "GCObject_internal.h"



@implementation GCLDSSealingSpouseStatusAttribute {

}

// Methods:
/** Initializes and returns a lDSSealingSpouseStatus.

 
 @return A new lDSSealingSpouseStatus.
*/
+(instancetype)lDSSealingSpouseStatus
{
	return [[self alloc] init];
}
/** Initializes and returns a lDSSealingSpouseStatus.

 @param value The value as a GCValue object.
 @return A new lDSSealingSpouseStatus.
*/
+(instancetype)lDSSealingSpouseStatusWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a lDSSealingSpouseStatus.

 @param value The value as an NSString.
 @return A new lDSSealingSpouseStatus.
*/
+(instancetype)lDSSealingSpouseStatusWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

