/*
 This file was autogenerated by tags.py 
 */

#import "GCLDSBaptismAttribute.h"

@implementation GCLDSBaptismAttribute {
	GCLDSBaptismStatusAttribute *_lDSBaptismStatus;
}

// Methods:
/// @name Initializing

/** Initializes and returns a lDSBaptism.

 
 @return A new lDSBaptism.
*/
+(instancetype)lDSBaptism
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a lDSBaptism.

 @param value The value as a GCValue object.
 @return A new lDSBaptism.
*/
+(instancetype)lDSBaptismWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a lDSBaptism.

 @param value The value as an NSString.
 @return A new lDSBaptism.
*/
+(instancetype)lDSBaptismWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:
@dynamic lDSBaptismStatus;

@end
