/*
 This file was autogenerated by tags.py 
 */

#import "GCLDSConfirmationAttribute.h"

@implementation GCLDSConfirmationAttribute {
	GCLDSBaptismStatusAttribute *_lDSBaptismStatus;
}

// Methods:
/// @name Initializing

/** Initializes and returns a lDSConfirmation.

 
 @return A new lDSConfirmation.
*/
+(instancetype)lDSConfirmation
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a lDSConfirmation.

 @param value The value as a GCValue object.
 @return A new lDSConfirmation.
*/
+(instancetype)lDSConfirmationWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a lDSConfirmation.

 @param value The value as an NSString.
 @return A new lDSConfirmation.
*/
+(instancetype)lDSConfirmationWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:
@dynamic lDSBaptismStatus;

@end
