/*
 This file was autogenerated by tags.py 
 */

#import "GCLDSBaptismAttribute.h"

@implementation GCLDSBaptismAttribute {
	GCLDSBaptismStatusAttribute *_lDSBaptismStatus;
	GCDateAttribute *_date;
	GCTempleAttribute *_temple;
	GCPlaceAttribute *_place;
	NSMutableArray *_sourceCitations;
	NSMutableArray *_sourceEmbeddeds;
	NSMutableArray *_noteReferences;
	NSMutableArray *_noteEmbeddeds;
}

// Methods:
/// @name Initializing

/** Initializes and returns a lDSBaptism.

 
 @return A new lDSBaptism.
*/
+(instancetype)lDSBaptism
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a lDSBaptism.

 @param value The value as a GCValue object.
 @return A new lDSBaptism.
*/
+(instancetype)lDSBaptismWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a lDSBaptism.

 @param value The value as an NSString.
 @return A new lDSBaptism.
*/
+(instancetype)lDSBaptismWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:
		_sourceCitations = [NSMutableArray array];
		_sourceEmbeddeds = [NSMutableArray array];
		_noteReferences = [NSMutableArray array];
		_noteEmbeddeds = [NSMutableArray array];
	}
	
	return self;
}


// Properties:
@dynamic lDSBaptismStatus;
@dynamic date;
@dynamic temple;
@dynamic place;
@dynamic sources;
@synthesize sourceCitations = _sourceCitations;
@dynamic mutableSourceCitations;
- (NSMutableArray *)mutableSourceCitations
{
	return [self mutableArrayValueForKey:@"sourceCitations"];
}

@synthesize sourceEmbeddeds = _sourceEmbeddeds;
@dynamic mutableSourceEmbeddeds;
- (NSMutableArray *)mutableSourceEmbeddeds
{
	return [self mutableArrayValueForKey:@"sourceEmbeddeds"];
}

@dynamic notes;
@synthesize noteReferences = _noteReferences;
@dynamic mutableNoteReferences;
- (NSMutableArray *)mutableNoteReferences
{
	return [self mutableArrayValueForKey:@"noteReferences"];
}

@synthesize noteEmbeddeds = _noteEmbeddeds;
@dynamic mutableNoteEmbeddeds;
- (NSMutableArray *)mutableNoteEmbeddeds
{
	return [self mutableArrayValueForKey:@"noteEmbeddeds"];
}


@end
