/*
 This file was autogenerated by tags.py 
 */

#import "GCMediaTypeAttribute.h"

#import "GCObject_internal.h"
#import "GCProperty_internal.h"



@implementation GCMediaTypeAttribute {

}

// Methods:
/** Initializes and returns a mediaType.

 
 @return A new mediaType.
*/
+(GCMediaTypeAttribute *)mediaType
{
	return [[self alloc] init];
}
/** Initializes and returns a mediaType.

 @param value The value as a GCValue object.
 @return A new mediaType.
*/
+(GCMediaTypeAttribute *)mediaTypeWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a mediaType.

 @param value The value as an NSString.
 @return A new mediaType.
*/
+(GCMediaTypeAttribute *)mediaTypeWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"mediaType"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

