/*
 This file was autogenerated by tags.py 
 */

#import "GCPersonalNameAttribute.h"

#import "GCGivenNameAttribute.h"
#import "GCNamePrefixAttribute.h"
#import "GCNameSuffixAttribute.h"
#import "GCNicknameAttribute.h"
#import "GCNoteEmbeddedAttribute.h"
#import "GCNoteReferenceRelationship.h"
#import "GCSourceCitationRelationship.h"
#import "GCSourceEmbeddedAttribute.h"
#import "GCSurnameAttribute.h"
#import "GCSurnamePrefixAttribute.h"

@implementation GCPersonalNameAttribute {
	GCNamePrefixAttribute *_namePrefix;
	GCGivenNameAttribute *_givenName;
	GCNicknameAttribute *_nickname;
	GCSurnamePrefixAttribute *_surnamePrefix;
	GCSurnameAttribute *_surname;
	GCNameSuffixAttribute *_nameSuffix;
	NSMutableArray *_sourceCitations;
	NSMutableArray *_sourceEmbeddeds;
	NSMutableArray *_noteReferences;
	NSMutableArray *_noteEmbeddeds;
}

// Methods:
/// @name Initializing

/** Initializes and returns a personalName.

 
 @return A new personalName.
*/
+(instancetype)personalName
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a personalName.

 @param value The value as a GCValue object.
 @return A new personalName.
*/
+(instancetype)personalNameWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a personalName.

 @param value The value as an NSString.
 @return A new personalName.
*/
+(instancetype)personalNameWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:
		_sourceCitations = [NSMutableArray array];
		_sourceEmbeddeds = [NSMutableArray array];
		_noteReferences = [NSMutableArray array];
		_noteEmbeddeds = [NSMutableArray array];
	}
	
	return self;
}


// Properties:
@dynamic namePrefix;
@dynamic givenName;
@dynamic nickname;
@dynamic surnamePrefix;
@dynamic surname;
@dynamic nameSuffix;
@dynamic sources;
@synthesize sourceCitations = _sourceCitations;

- (NSMutableArray *)mutableSourceCitations
{
	return [self mutableArrayValueForKey:@"sourceCitations"];
}

@synthesize sourceEmbeddeds = _sourceEmbeddeds;

- (NSMutableArray *)mutableSourceEmbeddeds
{
	return [self mutableArrayValueForKey:@"sourceEmbeddeds"];
}

@dynamic notes;
@synthesize noteReferences = _noteReferences;

- (NSMutableArray *)mutableNoteReferences
{
	return [self mutableArrayValueForKey:@"noteReferences"];
}

@synthesize noteEmbeddeds = _noteEmbeddeds;

- (NSMutableArray *)mutableNoteEmbeddeds
{
	return [self mutableArrayValueForKey:@"noteEmbeddeds"];
}


@end

