/*
 This file was autogenerated by tags.py 
 */

#import "GCPhoneNumberAttribute.h"

@implementation GCPhoneNumberAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a phoneNumber.

 
 @return A new phoneNumber.
*/
+(instancetype)phoneNumber
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a phoneNumber.

 @param value The value as a GCValue object.
 @return A new phoneNumber.
*/
+(instancetype)phoneNumberWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a phoneNumber.

 @param value The value as an NSString.
 @return A new phoneNumber.
*/
+(instancetype)phoneNumberWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
