/*
 This file was autogenerated by tags.py 
 */

#import "GCPlaceFormatSpecifierAttribute.h"

#import "GCObject_internal.h"

#import "GCPlaceFormatAttribute.h"

@implementation GCPlaceFormatSpecifierAttribute {
	GCPlaceFormatAttribute *_placeFormat;
}

// Methods:
/** Initializes and returns a placeFormatSpecifier.

 
 @return A new placeFormatSpecifier.
*/
+(instancetype)placeFormatSpecifier
{
	return [[self alloc] init];
}
/** Initializes and returns a placeFormatSpecifier.

 @param value The value as a GCValue object.
 @return A new placeFormatSpecifier.
*/
+(instancetype)placeFormatSpecifierWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a placeFormatSpecifier.

 @param value The value as an NSString.
 @return A new placeFormatSpecifier.
*/
+(instancetype)placeFormatSpecifierWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:
@dynamic placeFormat;

@end

