/*
 This file was autogenerated by tags.py 
 */

#import "GCPostalCodeAttribute.h"

#import "GCObject_internal.h"
#import "GCContext_internal.h"



@implementation GCPostalCodeAttribute {

}

// Methods:
/** Initializes and returns a postalCode.

 
 @return A new postalCode.
*/
+(GCPostalCodeAttribute *)postalCode
{
	return [[self alloc] init];
}
/** Initializes and returns a postalCode.

 @param value The value as a GCValue object.
 @return A new postalCode.
*/
+(GCPostalCodeAttribute *)postalCodeWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a postalCode.

 @param value The value as an NSString.
 @return A new postalCode.
*/
+(GCPostalCodeAttribute *)postalCodeWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"postalCode"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

