/*
 This file was autogenerated by tags.py 
 */

#import "GCResponsibleAgencyAttribute.h"

@implementation GCResponsibleAgencyAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a responsibleAgency.

 
 @return A new responsibleAgency.
*/
+(instancetype)responsibleAgency
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a responsibleAgency.

 @param value The value as a GCValue object.
 @return A new responsibleAgency.
*/
+(instancetype)responsibleAgencyWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a responsibleAgency.

 @param value The value as an NSString.
 @return A new responsibleAgency.
*/
+(instancetype)responsibleAgencyWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end
