/*
 This file was autogenerated by tags.py 
 */

#import "GCRecordFileNumberAttribute.h"

#import "GCObject_internal.h"



@implementation GCRecordFileNumberAttribute {

}

// Methods:
/** Initializes and returns a recordFileNumber.

 
 @return A new recordFileNumber.
*/
+(instancetype)recordFileNumber
{
	return [[self alloc] init];
}
/** Initializes and returns a recordFileNumber.

 @param value The value as a GCValue object.
 @return A new recordFileNumber.
*/
+(instancetype)recordFileNumberWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a recordFileNumber.

 @param value The value as an NSString.
 @return A new recordFileNumber.
*/
+(instancetype)recordFileNumberWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

