/*
 This file was autogenerated by tags.py 
 */

#import "GCSourceDataAttribute.h"

#import "GCObject_internal.h"

#import "GCEventsRecordedAttribute.h"
#import "GCNoteEmbeddedAttribute.h"
#import "GCNoteReferenceRelationship.h"
#import "GCResponsibleAgencyAttribute.h"

@implementation GCSourceDataAttribute {
	NSMutableArray *_eventsRecordeds;
	GCResponsibleAgencyAttribute *_responsibleAgency;
	NSMutableArray *_noteReferences;
	NSMutableArray *_noteEmbeddeds;
}

+ (GCTag *)gedTag
{
	return [GCTag tagWithClassName:@"GCSourceDataAttribute"];
}

// Methods:
/** Initializes and returns a sourceData.

 
 @return A new sourceData.
*/
+(GCSourceDataAttribute *)sourceData
{
	return [[self alloc] init];
}
/** Initializes and returns a sourceData.

 @param value The value as a GCValue object.
 @return A new sourceData.
*/
+(GCSourceDataAttribute *)sourceDataWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a sourceData.

 @param value The value as an NSString.
 @return A new sourceData.
*/
+(GCSourceDataAttribute *)sourceDataWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"sourceData"];
	
	if (self) {
		// initialize ivars, if any:
		_eventsRecordeds = [NSMutableArray array];
		_noteReferences = [NSMutableArray array];
		_noteEmbeddeds = [NSMutableArray array];
	}
	
	return self;
}


// Properties:
@dynamic eventsRecordeds;
@dynamic mutableEventsRecordeds;
@dynamic responsibleAgency;
@dynamic notes;
@dynamic noteReferences;
@dynamic mutableNoteReferences;
@dynamic noteEmbeddeds;
@dynamic mutableNoteEmbeddeds;

@end

