/*
 This file was autogenerated by tags.py 
 */

#import "GCSubmissionEntity.h"

#import "GCObject_internal.h"

#import "GCChangeInfoAttribute.h"
#import "GCFamilyFileAttribute.h"
#import "GCGenerationsOfAncestorsAttribute.h"
#import "GCGenerationsOfDescendantsAttribute.h"
#import "GCOrdinanceFlagAttribute.h"
#import "GCRecordIdNumberAttribute.h"
#import "GCSubmitterReferenceRelationship.h"
#import "GCTempleAttribute.h"
#import "GCUserReferenceNumberAttribute.h"

@implementation GCSubmissionEntity {
	GCSubmitterReferenceRelationship *_submitterReference;
	GCFamilyFileAttribute *_familyFile;
	GCTempleAttribute *_temple;
	GCGenerationsOfAncestorsAttribute *_generationsOfAncestors;
	GCGenerationsOfDescendantsAttribute *_generationsOfDescendants;
	GCOrdinanceFlagAttribute *_ordinanceFlag;
	NSMutableArray *_userReferenceNumbers;
	GCRecordIdNumberAttribute *_recordIdNumber;
	GCChangeInfoAttribute *_changeInfo;
}

+ (GCTag *)gedTag
{
	return [GCTag tagWithClassName:@"GCSubmissionEntity"];
}

// Methods:
/** Initializes and returns a submission.

 @param context The context in which to create the entity.
 @return A new submission.
*/
+(GCSubmissionEntity *)submissionInContext:(GCContext *)context
{
	return [[self alloc] initInContext:context];
}
- (id)initInContext:(GCContext *)context
{
	self = [super _initWithType:@"submission" inContext:context];
	
	if (self) {
		// initialize ivars, if any:
		_userReferenceNumbers = [NSMutableArray array];
	}
	
	return self;
}


// Properties:
@dynamic submitterReference;
@dynamic familyFile;
@dynamic temple;
@dynamic generationsOfAncestors;
@dynamic generationsOfDescendants;
@dynamic ordinanceFlag;
@dynamic userReferenceNumbers;
@dynamic mutableUserReferenceNumbers;
@dynamic recordIdNumber;
@dynamic changeInfo;

@end

