/*
 This file was autogenerated by tags.py 
 */

#import "GCSubmissionEntity.h"

#import "GCObject_internal.h"
#import "GCContext_internal.h"
#import "GCProperty_internal.h"

#import "GCChangeInfoAttribute.h"
#import "GCFamilyFileAttribute.h"
#import "GCGenerationsOfAncestorsAttribute.h"
#import "GCGenerationsOfDescendantsAttribute.h"
#import "GCOrdinanceFlagAttribute.h"
#import "GCRecordIdNumberAttribute.h"
#import "GCSubmitterReferenceRelationship.h"
#import "GCTempleAttribute.h"
#import "GCUserReferenceNumberAttribute.h"

@implementation GCSubmissionEntity {
	GCSubmitterReferenceRelationship *_submitterReference;
	GCFamilyFileAttribute *_familyFile;
	GCTempleAttribute *_temple;
	GCGenerationsOfAncestorsAttribute *_generationsOfAncestors;
	GCGenerationsOfDescendantsAttribute *_generationsOfDescendants;
	GCOrdinanceFlagAttribute *_ordinanceFlag;
	NSMutableArray *_userReferenceNumbers;
	GCRecordIdNumberAttribute *_recordIdNumber;
	GCChangeInfoAttribute *_changeInfo;
}

// Methods:
/** Initializes and returns a submission.

 @param context The context in which to create the entity.
 @return A new submission.
*/
+(GCSubmissionEntity *)submissionInContext:(GCContext *)context
{
	return [[self alloc] initInContext:context];
}
- (id)initInContext:(GCContext *)context
{
	self = [super _initWithType:@"submission" inContext:context];
	
	if (self) {
		// initialize ivars, if any:
		_userReferenceNumbers = [NSMutableArray array];
	}
	
	return self;
}


// Properties:

- (void)setSubmitterReference:(GCProperty *)obj
{
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] setSubmitterReference:_submitterReference];
	[self.context.undoManager setActionName:@"Undo submitterReference"]; //TODO
	
	if (_submitterReference) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_submitterReference = (id)obj;
}

- (GCSubmitterReferenceRelationship *)submitterReference
{
	return _submitterReference;
}


- (void)setFamilyFile:(GCProperty *)obj
{
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] setFamilyFile:_familyFile];
	[self.context.undoManager setActionName:@"Undo familyFile"]; //TODO
	
	if (_familyFile) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_familyFile = (id)obj;
}

- (GCFamilyFileAttribute *)familyFile
{
	return _familyFile;
}


- (void)setTemple:(GCProperty *)obj
{
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] setTemple:_temple];
	[self.context.undoManager setActionName:@"Undo temple"]; //TODO
	
	if (_temple) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_temple = (id)obj;
}

- (GCTempleAttribute *)temple
{
	return _temple;
}


- (void)setGenerationsOfAncestors:(GCProperty *)obj
{
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] setGenerationsOfAncestors:_generationsOfAncestors];
	[self.context.undoManager setActionName:@"Undo generationsOfAncestors"]; //TODO
	
	if (_generationsOfAncestors) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_generationsOfAncestors = (id)obj;
}

- (GCGenerationsOfAncestorsAttribute *)generationsOfAncestors
{
	return _generationsOfAncestors;
}


- (void)setGenerationsOfDescendants:(GCProperty *)obj
{
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] setGenerationsOfDescendants:_generationsOfDescendants];
	[self.context.undoManager setActionName:@"Undo generationsOfDescendants"]; //TODO
	
	if (_generationsOfDescendants) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_generationsOfDescendants = (id)obj;
}

- (GCGenerationsOfDescendantsAttribute *)generationsOfDescendants
{
	return _generationsOfDescendants;
}


- (void)setOrdinanceFlag:(GCProperty *)obj
{
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] setOrdinanceFlag:_ordinanceFlag];
	[self.context.undoManager setActionName:@"Undo ordinanceFlag"]; //TODO
	
	if (_ordinanceFlag) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_ordinanceFlag = (id)obj;
}

- (GCOrdinanceFlagAttribute *)ordinanceFlag
{
	return _ordinanceFlag;
}


- (NSMutableArray *)mutableUserReferenceNumbers {
    return [self mutableArrayValueForKey:@"userReferenceNumbers"];
}

- (NSUInteger)countOfUserReferenceNumbers {
	return [_userReferenceNumbers count];
}

- (id)objectInUserReferenceNumbersAtIndex:(NSUInteger)index {
    return [_userReferenceNumbers objectAtIndex:index];
}
 
- (void)insertObject:(GCProperty *)obj inUserReferenceNumbersAtIndex:(NSUInteger)index {
	NSParameterAssert([obj isKindOfClass:[GCUserReferenceNumberAttribute class]]);
	
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] removeObjectFromUserReferenceNumbersAtIndex:index];
	[self.context.undoManager setActionName:@"Undo userReferenceNumbers"]; //TODO
	
	if (obj.describedObject == self) {
		return;
	}
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	obj.describedObject = self;
    [_userReferenceNumbers insertObject:obj atIndex:index];
}

- (void)removeObjectFromUserReferenceNumbersAtIndex:(NSUInteger)index {
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] insertObject:_userReferenceNumbers[index] inUserReferenceNumbersAtIndex:index];
	[self.context.undoManager setActionName:@"Undo userReferenceNumbers"]; //TODO
	
	((GCProperty *)_userReferenceNumbers[index]).describedObject = nil;
	
    [_userReferenceNumbers removeObjectAtIndex:index];
}
	

- (void)setRecordIdNumber:(GCProperty *)obj
{
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] setRecordIdNumber:_recordIdNumber];
	[self.context.undoManager setActionName:@"Undo recordIdNumber"]; //TODO
	
	if (_recordIdNumber) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_recordIdNumber = (id)obj;
}

- (GCRecordIdNumberAttribute *)recordIdNumber
{
	return _recordIdNumber;
}


- (void)setChangeInfo:(GCProperty *)obj
{
	[(GCSubmissionEntity *)[self.context.undoManager prepareWithInvocationTarget:self] setChangeInfo:_changeInfo];
	[self.context.undoManager setActionName:@"Undo changeInfo"]; //TODO
	
	if (_changeInfo) {
		obj.describedObject = nil;
	}
	
	if (obj.describedObject) {
		[obj.describedObject.mutableProperties removeObject:obj];
	}
	
	obj.describedObject = self;
	
	_changeInfo = (id)obj;
}

- (GCChangeInfoAttribute *)changeInfo
{
	return _changeInfo;
}


@end

