/*
 This file was autogenerated by tags.py 
 */

#import "GCSubmissionReferenceRelationship.h"

#import "GCObject_internal.h"
#import "GCEntity_internal.h"



@implementation GCSubmissionReferenceRelationship {

}

// Methods:
/** Initializes and returns a submissionReference.

 
 @return A new submissionReference.
*/
+(GCSubmissionReferenceRelationship *)submissionReference
{
	return [[self alloc] init];
}
- (id)init
{
	self = [super _initWithType:@"submissionReference"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

