/*
 This file was autogenerated by tags.py 
 */

#import "GCSubmissionReferenceRelationship.h"

#import "GCObject_internal.h"



@implementation GCSubmissionReferenceRelationship {

}

// Methods:
/// @name Initializing

/** Initializes and returns a submissionReference.

 
 @return A new submissionReference.
*/
+(instancetype)submissionReference
{
	return [[self alloc] init];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

