/*
 This file was autogenerated by tags.py 
 */

#import "GCSurnameAttribute.h"

#import "GCObject_internal.h"



@implementation GCSurnameAttribute {

}

+ (GCTag *)gedTag
{
	return [GCTag tagWithClassName:@"GCSurnameAttribute"];
}

// Methods:
/** Initializes and returns a surname.

 
 @return A new surname.
*/
+(GCSurnameAttribute *)surname
{
	return [[self alloc] init];
}
/** Initializes and returns a surname.

 @param value The value as a GCValue object.
 @return A new surname.
*/
+(GCSurnameAttribute *)surnameWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/** Initializes and returns a surname.

 @param value The value as an NSString.
 @return A new surname.
*/
+(GCSurnameAttribute *)surnameWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (id)init
{
	self = [super _initWithType:@"surname"];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

