/*
 This file was autogenerated by tags.py 
 */

#import "GCTextAttribute.h"



@implementation GCTextAttribute {

}

// Methods:
/// @name Initializing

/** Initializes and returns a text.

 
 @return A new text.
*/
+(instancetype)text
{
	return [[self alloc] init];
}
/// @name Initializing

/** Initializes and returns a text.

 @param value The value as a GCValue object.
 @return A new text.
*/
+(instancetype)textWithValue:(GCValue *)value
{
	return [[self alloc] initWithValue:value];
}
/// @name Initializing

/** Initializes and returns a text.

 @param value The value as an NSString.
 @return A new text.
*/
+(instancetype)textWithGedcomStringValue:(NSString *)value
{
	return [[self alloc] initWithGedcomStringValue:value];
}
- (instancetype)init
{
	self = [super init];
	
	if (self) {
		// initialize ivars, if any:

	}
	
	return self;
}


// Properties:


@end

